Bug 14794 - liboil removal. Update of autogenerated files.
git-svn-id: http://publicsvn.songbirdnest.com/vendor/trunk@10350 37441250-4157-47a9-a2c9-f9fe3212d2d3

diff --git a/gst-plugins-bad/configure b/gst-plugins-bad/configure
--- a/gst-plugins-bad/configure
+++ b/gst-plugins-bad/configure
@@ -986,6 +986,8 @@ GLIB_CFLAGS
 GLIB_LIBS
 LIBOIL_CFLAGS
 LIBOIL_LIBS
+USE_LIBOIL_TRUE
+USE_LIBOIL_FALSE
 GST_CFLAGS
 GST_LIBS
 GST_TOOLS_DIR
@@ -1978,6 +1980,7 @@ Optional Features:
   --disable-external           disable building of plug-ins with external deps
   --enable-experimental        enable building of experimental plug-ins
   --enable-gtk-doc        use gtk-doc to build documentation default=no
+  --disable-liboil             disable liboil usage in some plugins
   --disable-aiffparse     disable dependency-less aiffparse plugin
   --disable-app           disable dependency-less app plugin
   --disable-bayer         disable dependency-less bayer plugin
@@ -5437,13 +5440,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5440: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5443: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5443: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5446: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5446: output\"" >&5)
+  (eval echo "\"\$as_me:5449: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6041,7 +6044,7 @@ if test "${lt_cv_ar_interface+set}" = set; then
 else
   lt_cv_ar_interface="ar"
   printf "$lt_simple_compile_test_code" > conftest.$ac_ext
-  (eval echo "\"\$as_me:6044: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:6047: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
   (eval "$AR -NOLOGO -OUT:conftest.lib conftest.$ac_objext" &>conftest.err)
@@ -6659,7 +6662,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6662 "configure"' > conftest.$ac_ext
+  echo '#line 6665 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8199,11 +8202,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8202: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8205: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8206: \$? = $ac_status" >&5
+   echo "$as_me:8209: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8523,11 +8526,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8526: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8529: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8530: \$? = $ac_status" >&5
+   echo "$as_me:8533: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8628,11 +8631,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8631: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8634: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8635: \$? = $ac_status" >&5
+   echo "$as_me:8638: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8683,11 +8686,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8686: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8689: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8690: \$? = $ac_status" >&5
+   echo "$as_me:8693: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11520,7 +11523,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11523 "configure"
+#line 11526 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11620,7 +11623,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11623 "configure"
+#line 11626 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18826,11 +18829,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18829: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18832: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18833: \$? = $ac_status" >&5
+   echo "$as_me:18836: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18925,11 +18928,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18928: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18931: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18932: \$? = $ac_status" >&5
+   echo "$as_me:18935: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18977,11 +18980,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18980: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18983: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18984: \$? = $ac_status" >&5
+   echo "$as_me:18987: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -24015,6 +24018,49 @@ echo "$as_me: error: This package requires GLib >= $GLIB_REQ to compile." >&2;}
 
 
 
+echo
+{ echo "$as_me:$LINENO: *** checking feature: liboil usage in some plugins ***" >&5
+echo "$as_me: *** checking feature: liboil usage in some plugins ***" >&6;}
+if test "x" != "x"
+then
+  { echo "$as_me:$LINENO: *** for plug-ins:  ***" >&5
+echo "$as_me: *** for plug-ins:  ***" >&6;}
+fi
+NOUSE=
+if test "x$USE_LIBOIL" = "xno"; then
+  NOUSE="yes"
+fi
+# Check whether --enable-liboil was given.
+if test "${enable_liboil+set}" = set; then
+  enableval=$enable_liboil;  case "${enableval}" in
+      yes) USE_LIBOIL=yes;;
+      no) USE_LIBOIL=no;;
+      *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-liboil" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-liboil" >&2;}
+   { (exit 1); exit 1; }; } ;;
+    esac
+else
+   USE_LIBOIL=yes
+fi
+
+if test "x$NOUSE" = "xyes"; then
+  USE_LIBOIL="no"
+  { echo "$as_me:$LINENO: WARNING: ***  pre-configured not to be built" >&5
+echo "$as_me: WARNING: ***  pre-configured not to be built" >&2;}
+fi
+NOUSE=
+
+
+if test x$USE_LIBOIL = xyes; then
+
+  gst_check_save_LIBS=$LIBS
+  gst_check_save_LDFLAGS=$LDFLAGS
+  gst_check_save_CFLAGS=$CFLAGS
+  gst_check_save_CPPFLAGS=$CPPFLAGS
+  gst_check_save_CXXFLAGS=$CXXFLAGS
+
+  HAVE_LIBOIL=no
+
 
 pkg_failed=no
 { echo "$as_me:$LINENO: checking for LIBOIL" >&5
@@ -24025,12 +24071,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_LIBOIL_CFLAGS="$LIBOIL_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liboil-0.3 >= 0.3.8\"") >&5
-  ($PKG_CONFIG --exists --print-errors "liboil-0.3 >= 0.3.8") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liboil-0.3 >= 0.3.14\"") >&5
+  ($PKG_CONFIG --exists --print-errors "liboil-0.3 >= 0.3.14") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_LIBOIL_CFLAGS=`$PKG_CONFIG --cflags "liboil-0.3 >= 0.3.8" 2>/dev/null`
+  pkg_cv_LIBOIL_CFLAGS=`$PKG_CONFIG --cflags "liboil-0.3 >= 0.3.14" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -24043,12 +24089,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_LIBOIL_LIBS="$LIBOIL_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liboil-0.3 >= 0.3.8\"") >&5
-  ($PKG_CONFIG --exists --print-errors "liboil-0.3 >= 0.3.8") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liboil-0.3 >= 0.3.14\"") >&5
+  ($PKG_CONFIG --exists --print-errors "liboil-0.3 >= 0.3.14") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_LIBOIL_LIBS=`$PKG_CONFIG --libs "liboil-0.3 >= 0.3.8" 2>/dev/null`
+  pkg_cv_LIBOIL_LIBS=`$PKG_CONFIG --libs "liboil-0.3 >= 0.3.14" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -24058,7 +24104,7 @@ else
 fi
 
 if test $pkg_failed = yes; then
-	LIBOIL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "liboil-0.3 >= 0.3.8"`
+	LIBOIL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "liboil-0.3 >= 0.3.14"`
 	# Put the nasty error message in config.log where it belongs
 	echo "$LIBOIL_PKG_ERRORS" 1>&5
 
@@ -24072,11 +24118,55 @@ else
 echo "${ECHO_T}yes" >&6; }
 	HAVE_LIBOIL=yes
 fi
-if test "x$HAVE_LIBOIL" != "xyes"; then
-  { { echo "$as_me:$LINENO: error: liboil-0.3.8 or later is required" >&5
-echo "$as_me: error: liboil-0.3.8 or later is required" >&2;}
-   { (exit 1); exit 1; }; }
+  if test "x$HAVE_LIBOIL" = "xyes"; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBOIL 1
+_ACEOF
+
+  fi
+
+
+  LIBS=$gst_check_save_LIBS
+  LDFLAGS=$gst_check_save_LDFLAGS
+  CFLAGS=$gst_check_save_CFLAGS
+  CPPFLAGS=$gst_check_save_CPPFLAGS
+  CXXFLAGS=$gst_check_save_CXXFLAGS
+
+    if test x$HAVE_LIBOIL = xno; then
+    USE_LIBOIL=no
+  else
+    :
+  fi
 fi
+if test x$USE_LIBOIL = xyes; then
+  :
+  if test "x" != "x"; then
+    GST_PLUGINS_YES="\t\n$GST_PLUGINS_YES"
+  fi
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBOIL
+_ACEOF
+
+else
+  :
+  if test "x" != "x"; then
+    GST_PLUGINS_NO="\t\n$GST_PLUGINS_NO"
+  fi
+  :
+fi
+
+
+if test x$USE_LIBOIL = xyes; then
+  USE_LIBOIL_TRUE=
+  USE_LIBOIL_FALSE='#'
+else
+  USE_LIBOIL_TRUE='#'
+  USE_LIBOIL_FALSE=
+fi
+
+
 
 
 
@@ -43317,6 +43407,13 @@ echo "$as_me: error: conditional \"HAVE_GCC_ASM\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${USE_LIBOIL_TRUE}" && test -z "${USE_LIBOIL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"USE_LIBOIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"USE_LIBOIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_GST_CHECK_TRUE}" && test -z "${HAVE_GST_CHECK_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_GST_CHECK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -45564,6 +45661,8 @@ GLIB_CFLAGS!$GLIB_CFLAGS$ac_delim
 GLIB_LIBS!$GLIB_LIBS$ac_delim
 LIBOIL_CFLAGS!$LIBOIL_CFLAGS$ac_delim
 LIBOIL_LIBS!$LIBOIL_LIBS$ac_delim
+USE_LIBOIL_TRUE!$USE_LIBOIL_TRUE$ac_delim
+USE_LIBOIL_FALSE!$USE_LIBOIL_FALSE$ac_delim
 GST_CFLAGS!$GST_CFLAGS$ac_delim
 GST_LIBS!$GST_LIBS$ac_delim
 GST_TOOLS_DIR!$GST_TOOLS_DIR$ac_delim
@@ -45631,8 +45730,6 @@ USE_PLUGIN_H264PARSE_FALSE!$USE_PLUGIN_H264PARSE_FALSE$ac_delim
 USE_PLUGIN_LIBRFB_TRUE!$USE_PLUGIN_LIBRFB_TRUE$ac_delim
 USE_PLUGIN_LIBRFB_FALSE!$USE_PLUGIN_LIBRFB_FALSE$ac_delim
 USE_PLUGIN_MODPLUG_TRUE!$USE_PLUGIN_MODPLUG_TRUE$ac_delim
-USE_PLUGIN_MODPLUG_FALSE!$USE_PLUGIN_MODPLUG_FALSE$ac_delim
-USE_PLUGIN_MPEGTSPARSE_TRUE!$USE_PLUGIN_MPEGTSPARSE_TRUE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -45674,6 +45771,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+USE_PLUGIN_MODPLUG_FALSE!$USE_PLUGIN_MODPLUG_FALSE$ac_delim
+USE_PLUGIN_MPEGTSPARSE_TRUE!$USE_PLUGIN_MPEGTSPARSE_TRUE$ac_delim
 USE_PLUGIN_MPEGTSPARSE_FALSE!$USE_PLUGIN_MPEGTSPARSE_FALSE$ac_delim
 USE_PLUGIN_MPEG4VIDEOPARSE_TRUE!$USE_PLUGIN_MPEG4VIDEOPARSE_TRUE$ac_delim
 USE_PLUGIN_MPEG4VIDEOPARSE_FALSE!$USE_PLUGIN_MPEG4VIDEOPARSE_FALSE$ac_delim
@@ -45769,8 +45868,6 @@ DVDNAV_CFLAGS!$DVDNAV_CFLAGS$ac_delim
 USE_DVDNAV_TRUE!$USE_DVDNAV_TRUE$ac_delim
 USE_DVDNAV_FALSE!$USE_DVDNAV_FALSE$ac_delim
 EXIF_CFLAGS!$EXIF_CFLAGS$ac_delim
-EXIF_LIBS!$EXIF_LIBS$ac_delim
-IPTC_CFLAGS!$IPTC_CFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -45812,6 +45909,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+EXIF_LIBS!$EXIF_LIBS$ac_delim
+IPTC_CFLAGS!$IPTC_CFLAGS$ac_delim
 IPTC_LIBS!$IPTC_LIBS$ac_delim
 XMP_CFLAGS!$XMP_CFLAGS$ac_delim
 XMP_LIBS!$XMP_LIBS$ac_delim
@@ -45907,8 +46006,6 @@ USE_SDL_FALSE!$USE_SDL_FALSE$ac_delim
 SNDFILE_CFLAGS!$SNDFILE_CFLAGS$ac_delim
 SNDFILE_LIBS!$SNDFILE_LIBS$ac_delim
 USE_SNDFILE_TRUE!$USE_SNDFILE_TRUE$ac_delim
-USE_SNDFILE_FALSE!$USE_SNDFILE_FALSE$ac_delim
-SOUNDTOUCH_CFLAGS!$SOUNDTOUCH_CFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -45950,6 +46047,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+USE_SNDFILE_FALSE!$USE_SNDFILE_FALSE$ac_delim
+SOUNDTOUCH_CFLAGS!$SOUNDTOUCH_CFLAGS$ac_delim
 SOUNDTOUCH_LIBS!$SOUNDTOUCH_LIBS$ac_delim
 USE_SOUNDTOUCH_TRUE!$USE_SOUNDTOUCH_TRUE$ac_delim
 USE_SOUNDTOUCH_FALSE!$USE_SOUNDTOUCH_FALSE$ac_delim
@@ -45995,7 +46094,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 43; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 45; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
diff --git a/gst-plugins-base/configure b/gst-plugins-base/configure
--- a/gst-plugins-base/configure
+++ b/gst-plugins-base/configure
@@ -985,6 +985,8 @@ GLIB_CFLAGS
 GLIB_LIBS
 LIBOIL_CFLAGS
 LIBOIL_LIBS
+USE_LIBOIL_TRUE
+USE_LIBOIL_FALSE
 GST_CFLAGS
 GST_LIBS
 GST_TOOLS_DIR
@@ -1767,6 +1769,7 @@ Optional Features:
   --enable-experimental        enable building of experimental plug-ins
   --disable-largefile     omit support for large files
   --enable-gtk-doc        use gtk-doc to build documentation default=no
+  --disable-liboil             disable liboil usage in some plugins
   --disable-adder         disable dependency-less adder plugin
   --disable-audioconvert  disable dependency-less audioconvert plugin
   --disable-audiorate     disable dependency-less audiorate plugin
@@ -5079,13 +5082,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5082: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5085: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5085: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5088: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5088: output\"" >&5)
+  (eval echo "\"\$as_me:5091: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5683,7 +5686,7 @@ if test "${lt_cv_ar_interface+set}" = set; then
 else
   lt_cv_ar_interface="ar"
   printf "$lt_simple_compile_test_code" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5686: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5689: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
   (eval "$AR -NOLOGO -OUT:conftest.lib conftest.$ac_objext" &>conftest.err)
@@ -6301,7 +6304,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6304 "configure"' > conftest.$ac_ext
+  echo '#line 6307 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7839,11 +7842,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7842: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7845: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7846: \$? = $ac_status" >&5
+   echo "$as_me:7849: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8163,11 +8166,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8166: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8169: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8170: \$? = $ac_status" >&5
+   echo "$as_me:8173: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8268,11 +8271,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8271: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8274: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8275: \$? = $ac_status" >&5
+   echo "$as_me:8278: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8323,11 +8326,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8326: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8329: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8330: \$? = $ac_status" >&5
+   echo "$as_me:8333: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11160,7 +11163,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11163 "configure"
+#line 11166 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11260,7 +11263,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11263 "configure"
+#line 11266 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21260,6 +21263,49 @@ echo "$as_me: error: This package requires GLib >= $GLIB_REQ to compile." >&2;}
 
 
 
+echo
+{ echo "$as_me:$LINENO: *** checking feature: liboil usage in some plugins ***" >&5
+echo "$as_me: *** checking feature: liboil usage in some plugins ***" >&6;}
+if test "x" != "x"
+then
+  { echo "$as_me:$LINENO: *** for plug-ins:  ***" >&5
+echo "$as_me: *** for plug-ins:  ***" >&6;}
+fi
+NOUSE=
+if test "x$USE_LIBOIL" = "xno"; then
+  NOUSE="yes"
+fi
+# Check whether --enable-liboil was given.
+if test "${enable_liboil+set}" = set; then
+  enableval=$enable_liboil;  case "${enableval}" in
+      yes) USE_LIBOIL=yes;;
+      no) USE_LIBOIL=no;;
+      *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-liboil" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-liboil" >&2;}
+   { (exit 1); exit 1; }; } ;;
+    esac
+else
+   USE_LIBOIL=yes
+fi
+
+if test "x$NOUSE" = "xyes"; then
+  USE_LIBOIL="no"
+  { echo "$as_me:$LINENO: WARNING: ***  pre-configured not to be built" >&5
+echo "$as_me: WARNING: ***  pre-configured not to be built" >&2;}
+fi
+NOUSE=
+
+
+if test x$USE_LIBOIL = xyes; then
+
+  gst_check_save_LIBS=$LIBS
+  gst_check_save_LDFLAGS=$LDFLAGS
+  gst_check_save_CFLAGS=$CFLAGS
+  gst_check_save_CPPFLAGS=$CPPFLAGS
+  gst_check_save_CXXFLAGS=$CXXFLAGS
+
+  HAVE_LIBOIL=no
+
 
 pkg_failed=no
 { echo "$as_me:$LINENO: checking for LIBOIL" >&5
@@ -21317,11 +21363,55 @@ else
 echo "${ECHO_T}yes" >&6; }
 	HAVE_LIBOIL=yes
 fi
-if test "x$HAVE_LIBOIL" != "xyes"; then
-  { { echo "$as_me:$LINENO: error: liboil-0.3.14 or later is required" >&5
-echo "$as_me: error: liboil-0.3.14 or later is required" >&2;}
-   { (exit 1); exit 1; }; }
+  if test "x$HAVE_LIBOIL" = "xyes"; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBOIL 1
+_ACEOF
+
+  fi
+
+
+  LIBS=$gst_check_save_LIBS
+  LDFLAGS=$gst_check_save_LDFLAGS
+  CFLAGS=$gst_check_save_CFLAGS
+  CPPFLAGS=$gst_check_save_CPPFLAGS
+  CXXFLAGS=$gst_check_save_CXXFLAGS
+
+    if test x$HAVE_LIBOIL = xno; then
+    USE_LIBOIL=no
+  else
+    :
+  fi
 fi
+if test x$USE_LIBOIL = xyes; then
+  :
+  if test "x" != "x"; then
+    GST_PLUGINS_YES="\t\n$GST_PLUGINS_YES"
+  fi
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBOIL
+_ACEOF
+
+else
+  :
+  if test "x" != "x"; then
+    GST_PLUGINS_NO="\t\n$GST_PLUGINS_NO"
+  fi
+  :
+fi
+
+
+if test x$USE_LIBOIL = xyes; then
+  USE_LIBOIL_TRUE=
+  USE_LIBOIL_FALSE='#'
+else
+  USE_LIBOIL_TRUE='#'
+  USE_LIBOIL_FALSE=
+fi
+
+
 
 
 
@@ -29356,6 +29446,13 @@ echo "$as_me: error: conditional \"HAVE_SYS_SOCKET_H\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${USE_LIBOIL_TRUE}" && test -z "${USE_LIBOIL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"USE_LIBOIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"USE_LIBOIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_GST_CHECK_TRUE}" && test -z "${HAVE_GST_CHECK_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_GST_CHECK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -30878,6 +30975,8 @@ GLIB_CFLAGS!$GLIB_CFLAGS$ac_delim
 GLIB_LIBS!$GLIB_LIBS$ac_delim
 LIBOIL_CFLAGS!$LIBOIL_CFLAGS$ac_delim
 LIBOIL_LIBS!$LIBOIL_LIBS$ac_delim
+USE_LIBOIL_TRUE!$USE_LIBOIL_TRUE$ac_delim
+USE_LIBOIL_FALSE!$USE_LIBOIL_FALSE$ac_delim
 GST_CFLAGS!$GST_CFLAGS$ac_delim
 GST_LIBS!$GST_LIBS$ac_delim
 GST_TOOLS_DIR!$GST_TOOLS_DIR$ac_delim
@@ -30946,8 +31045,6 @@ X_EXTRA_LIBS!$X_EXTRA_LIBS$ac_delim
 HAVE_X!$HAVE_X$ac_delim
 USE_X_TRUE!$USE_X_TRUE$ac_delim
 USE_X_FALSE!$USE_X_FALSE$ac_delim
-XVIDEO_LIBS!$XVIDEO_LIBS$ac_delim
-USE_XVIDEO_TRUE!$USE_XVIDEO_TRUE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -30989,6 +31086,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+XVIDEO_LIBS!$XVIDEO_LIBS$ac_delim
+USE_XVIDEO_TRUE!$USE_XVIDEO_TRUE$ac_delim
 USE_XVIDEO_FALSE!$USE_XVIDEO_FALSE$ac_delim
 HAVE_XSHM!$HAVE_XSHM$ac_delim
 XSHM_LIBS!$XSHM_LIBS$ac_delim
@@ -31051,7 +31150,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 60; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 62; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
diff --git a/gst-plugins-good/configure b/gst-plugins-good/configure
--- a/gst-plugins-good/configure
+++ b/gst-plugins-good/configure
@@ -995,6 +995,8 @@ GLIB_CFLAGS
 GLIB_LIBS
 LIBOIL_CFLAGS
 LIBOIL_LIBS
+USE_LIBOIL_TRUE
+USE_LIBOIL_FALSE
 GST_CFLAGS
 GST_LIBS
 GST_TOOLS_DIR
@@ -1929,6 +1931,7 @@ Optional Features:
   --enable-experimental        enable building of experimental plug-ins
   --disable-schemas-install	Disable the schemas installation
   --enable-gtk-doc        use gtk-doc to build documentation default=no
+  --disable-liboil             disable liboil usage in some plugins
   --disable-gconftool          disable GConf schemas
   --disable-videofilter   disable dependency-less videofilter plugin
   --disable-alpha         disable dependency-less alpha plugin
@@ -5291,13 +5294,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5294: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5297: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5297: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5300: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5300: output\"" >&5)
+  (eval echo "\"\$as_me:5303: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5895,7 +5898,7 @@ if test "${lt_cv_ar_interface+set}" = set; then
 else
   lt_cv_ar_interface="ar"
   printf "$lt_simple_compile_test_code" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5898: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5901: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
   (eval "$AR -NOLOGO -OUT:conftest.lib conftest.$ac_objext" &>conftest.err)
@@ -6513,7 +6516,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6516 "configure"' > conftest.$ac_ext
+  echo '#line 6519 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8053,11 +8056,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8056: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8059: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8060: \$? = $ac_status" >&5
+   echo "$as_me:8063: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8377,11 +8380,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8380: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8383: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8384: \$? = $ac_status" >&5
+   echo "$as_me:8387: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8482,11 +8485,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8485: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8488: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8489: \$? = $ac_status" >&5
+   echo "$as_me:8492: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8537,11 +8540,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8540: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8543: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8544: \$? = $ac_status" >&5
+   echo "$as_me:8547: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11374,7 +11377,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11377 "configure"
+#line 11380 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11474,7 +11477,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11477 "configure"
+#line 11480 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18680,11 +18683,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18683: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18686: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18687: \$? = $ac_status" >&5
+   echo "$as_me:18690: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18779,11 +18782,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18782: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18785: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18786: \$? = $ac_status" >&5
+   echo "$as_me:18789: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18831,11 +18834,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18834: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18837: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18838: \$? = $ac_status" >&5
+   echo "$as_me:18841: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -25502,6 +25505,49 @@ echo "$as_me: error: This package requires GLib >= $GLIB_REQ to compile." >&2;}
 
 
 
+echo
+{ echo "$as_me:$LINENO: *** checking feature: liboil usage in some plugins ***" >&5
+echo "$as_me: *** checking feature: liboil usage in some plugins ***" >&6;}
+if test "x" != "x"
+then
+  { echo "$as_me:$LINENO: *** for plug-ins:  ***" >&5
+echo "$as_me: *** for plug-ins:  ***" >&6;}
+fi
+NOUSE=
+if test "x$USE_LIBOIL" = "xno"; then
+  NOUSE="yes"
+fi
+# Check whether --enable-liboil was given.
+if test "${enable_liboil+set}" = set; then
+  enableval=$enable_liboil;  case "${enableval}" in
+      yes) USE_LIBOIL=yes;;
+      no) USE_LIBOIL=no;;
+      *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-liboil" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-liboil" >&2;}
+   { (exit 1); exit 1; }; } ;;
+    esac
+else
+   USE_LIBOIL=yes
+fi
+
+if test "x$NOUSE" = "xyes"; then
+  USE_LIBOIL="no"
+  { echo "$as_me:$LINENO: WARNING: ***  pre-configured not to be built" >&5
+echo "$as_me: WARNING: ***  pre-configured not to be built" >&2;}
+fi
+NOUSE=
+
+
+if test x$USE_LIBOIL = xyes; then
+
+  gst_check_save_LIBS=$LIBS
+  gst_check_save_LDFLAGS=$LDFLAGS
+  gst_check_save_CFLAGS=$CFLAGS
+  gst_check_save_CPPFLAGS=$CPPFLAGS
+  gst_check_save_CXXFLAGS=$CXXFLAGS
+
+  HAVE_LIBOIL=no
+
 
 pkg_failed=no
 { echo "$as_me:$LINENO: checking for LIBOIL" >&5
@@ -25512,12 +25558,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_LIBOIL_CFLAGS="$LIBOIL_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liboil-0.3 >= 0.3.8\"") >&5
-  ($PKG_CONFIG --exists --print-errors "liboil-0.3 >= 0.3.8") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liboil-0.3 >= 0.3.14\"") >&5
+  ($PKG_CONFIG --exists --print-errors "liboil-0.3 >= 0.3.14") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_LIBOIL_CFLAGS=`$PKG_CONFIG --cflags "liboil-0.3 >= 0.3.8" 2>/dev/null`
+  pkg_cv_LIBOIL_CFLAGS=`$PKG_CONFIG --cflags "liboil-0.3 >= 0.3.14" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -25530,12 +25576,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_LIBOIL_LIBS="$LIBOIL_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liboil-0.3 >= 0.3.8\"") >&5
-  ($PKG_CONFIG --exists --print-errors "liboil-0.3 >= 0.3.8") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liboil-0.3 >= 0.3.14\"") >&5
+  ($PKG_CONFIG --exists --print-errors "liboil-0.3 >= 0.3.14") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_LIBOIL_LIBS=`$PKG_CONFIG --libs "liboil-0.3 >= 0.3.8" 2>/dev/null`
+  pkg_cv_LIBOIL_LIBS=`$PKG_CONFIG --libs "liboil-0.3 >= 0.3.14" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -25545,7 +25591,7 @@ else
 fi
 
 if test $pkg_failed = yes; then
-	LIBOIL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "liboil-0.3 >= 0.3.8"`
+	LIBOIL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "liboil-0.3 >= 0.3.14"`
 	# Put the nasty error message in config.log where it belongs
 	echo "$LIBOIL_PKG_ERRORS" 1>&5
 
@@ -25559,11 +25605,55 @@ else
 echo "${ECHO_T}yes" >&6; }
 	HAVE_LIBOIL=yes
 fi
-if test "x$HAVE_LIBOIL" != "xyes"; then
-  { { echo "$as_me:$LINENO: error: liboil-0.3.8 or later is required" >&5
-echo "$as_me: error: liboil-0.3.8 or later is required" >&2;}
-   { (exit 1); exit 1; }; }
+  if test "x$HAVE_LIBOIL" = "xyes"; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBOIL 1
+_ACEOF
+
+  fi
+
+
+  LIBS=$gst_check_save_LIBS
+  LDFLAGS=$gst_check_save_LDFLAGS
+  CFLAGS=$gst_check_save_CFLAGS
+  CPPFLAGS=$gst_check_save_CPPFLAGS
+  CXXFLAGS=$gst_check_save_CXXFLAGS
+
+    if test x$HAVE_LIBOIL = xno; then
+    USE_LIBOIL=no
+  else
+    :
+  fi
 fi
+if test x$USE_LIBOIL = xyes; then
+  :
+  if test "x" != "x"; then
+    GST_PLUGINS_YES="\t\n$GST_PLUGINS_YES"
+  fi
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBOIL
+_ACEOF
+
+else
+  :
+  if test "x" != "x"; then
+    GST_PLUGINS_NO="\t\n$GST_PLUGINS_NO"
+  fi
+  :
+fi
+
+
+if test x$USE_LIBOIL = xyes; then
+  USE_LIBOIL_TRUE=
+  USE_LIBOIL_FALSE='#'
+else
+  USE_LIBOIL_TRUE='#'
+  USE_LIBOIL_FALSE=
+fi
+
+
 
 
 
@@ -41163,6 +41253,13 @@ echo "$as_me: error: conditional \"GST_HAVE_MMAP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${USE_LIBOIL_TRUE}" && test -z "${USE_LIBOIL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"USE_LIBOIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"USE_LIBOIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_GST_CHECK_TRUE}" && test -z "${HAVE_GST_CHECK_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_GST_CHECK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -43193,6 +43290,8 @@ GLIB_CFLAGS!$GLIB_CFLAGS$ac_delim
 GLIB_LIBS!$GLIB_LIBS$ac_delim
 LIBOIL_CFLAGS!$LIBOIL_CFLAGS$ac_delim
 LIBOIL_LIBS!$LIBOIL_LIBS$ac_delim
+USE_LIBOIL_TRUE!$USE_LIBOIL_TRUE$ac_delim
+USE_LIBOIL_FALSE!$USE_LIBOIL_FALSE$ac_delim
 GST_CFLAGS!$GST_CFLAGS$ac_delim
 GST_LIBS!$GST_LIBS$ac_delim
 GST_TOOLS_DIR!$GST_TOOLS_DIR$ac_delim
@@ -43251,8 +43350,6 @@ USE_PLUGIN_AUTODETECT_TRUE!$USE_PLUGIN_AUTODETECT_TRUE$ac_delim
 USE_PLUGIN_AUTODETECT_FALSE!$USE_PLUGIN_AUTODETECT_FALSE$ac_delim
 USE_PLUGIN_AVI_TRUE!$USE_PLUGIN_AVI_TRUE$ac_delim
 USE_PLUGIN_AVI_FALSE!$USE_PLUGIN_AVI_FALSE$ac_delim
-USE_PLUGIN_CUTTER_TRUE!$USE_PLUGIN_CUTTER_TRUE$ac_delim
-USE_PLUGIN_CUTTER_FALSE!$USE_PLUGIN_CUTTER_FALSE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -43294,6 +43391,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+USE_PLUGIN_CUTTER_TRUE!$USE_PLUGIN_CUTTER_TRUE$ac_delim
+USE_PLUGIN_CUTTER_FALSE!$USE_PLUGIN_CUTTER_FALSE$ac_delim
 USE_PLUGIN_DEBUG_TRUE!$USE_PLUGIN_DEBUG_TRUE$ac_delim
 USE_PLUGIN_DEBUG_FALSE!$USE_PLUGIN_DEBUG_FALSE$ac_delim
 USE_PLUGIN_EFFECTV_TRUE!$USE_PLUGIN_EFFECTV_TRUE$ac_delim
@@ -43389,8 +43488,6 @@ XSHM_LIBS!$XSHM_LIBS$ac_delim
 USE_XSHM_TRUE!$USE_XSHM_TRUE$ac_delim
 USE_XSHM_FALSE!$USE_XSHM_FALSE$ac_delim
 USE_XVIDEO_TRUE!$USE_XVIDEO_TRUE$ac_delim
-USE_XVIDEO_FALSE!$USE_XVIDEO_FALSE$ac_delim
-AALIB_CONFIG!$AALIB_CONFIG$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -43432,6 +43529,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+USE_XVIDEO_FALSE!$USE_XVIDEO_FALSE$ac_delim
+AALIB_CONFIG!$AALIB_CONFIG$ac_delim
 AALIB_CFLAGS!$AALIB_CFLAGS$ac_delim
 AALIB_LIBS!$AALIB_LIBS$ac_delim
 USE_AALIB_TRUE!$USE_AALIB_TRUE$ac_delim
@@ -43527,8 +43626,6 @@ GST_LT_LDFLAGS!$GST_LT_LDFLAGS$ac_delim
 GST_CXXFLAGS!$GST_CXXFLAGS$ac_delim
 GST_ALL_LDFLAGS!$GST_ALL_LDFLAGS$ac_delim
 GST_PLUGIN_LDFLAGS!$GST_PLUGIN_LDFLAGS$ac_delim
-LIBOBJS!$LIBOBJS$ac_delim
-LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -43563,6 +43660,51 @@ N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
 ' >>$CONFIG_STATUS <conf$$subs.sed
 rm -f conf$$subs.sed
 cat >>$CONFIG_STATUS <<_ACEOF
+CEOF$ac_eof
+_ACEOF
+
+
+ac_delim='%!_!# '
+for ac_last_try in false false false false false :; do
+  cat >conf$$subs.sed <<_ACEOF
+LIBOBJS!$LIBOBJS$ac_delim
+LTLIBOBJS!$LTLIBOBJS$ac_delim
+_ACEOF
+
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 2; then
+    break
+  elif $ac_last_try; then
+    { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
+echo "$as_me: error: could not make $CONFIG_STATUS" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    ac_delim="$ac_delim!$ac_delim _$ac_delim!! "
+  fi
+done
+
+ac_eof=`sed -n '/^CEOF[0-9]*$/s/CEOF/0/p' conf$$subs.sed`
+if test -n "$ac_eof"; then
+  ac_eof=`echo "$ac_eof" | sort -nru | sed 1q`
+  ac_eof=`expr $ac_eof + 1`
+fi
+
+cat >>$CONFIG_STATUS <<_ACEOF
+cat >"\$tmp/subs-6.sed" <<\CEOF$ac_eof
+/@[a-zA-Z_][a-zA-Z_0-9]*@/!b end
+_ACEOF
+sed '
+s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g
+s/^/s,@/; s/!/@,|#_!!_#|/
+:n
+t n
+s/'"$ac_delim"'$/,g/; t
+s/$/\\/; p
+N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
+' >>$CONFIG_STATUS <conf$$subs.sed
+rm -f conf$$subs.sed
+cat >>$CONFIG_STATUS <<_ACEOF
+:end
+s/|#_!!_#|//g
 CEOF$ac_eof
 _ACEOF
 
@@ -43810,7 +43952,7 @@ s&@abs_builddir@&$ac_abs_builddir&;t t
 s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 s&@INSTALL@&$ac_INSTALL&;t t
 $ac_datarootdir_hack
-" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" | sed -f "$tmp/subs-3.sed" | sed -f "$tmp/subs-4.sed" | sed -f "$tmp/subs-5.sed" | sed 's/|#_!!_#|//g' >$tmp/out
+" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" | sed -f "$tmp/subs-3.sed" | sed -f "$tmp/subs-4.sed" | sed -f "$tmp/subs-5.sed" | sed -f "$tmp/subs-6.sed" >$tmp/out
 
 test -z "$ac_datarootdir_hack$ac_datarootdir_seen" &&
   { ac_out=`sed -n '/\${datarootdir}/p' "$tmp/out"`; test -n "$ac_out"; } &&
diff --git a/gst-plugins-ugly/configure b/gst-plugins-ugly/configure
--- a/gst-plugins-ugly/configure
+++ b/gst-plugins-ugly/configure
@@ -978,6 +978,8 @@ GLIB_CFLAGS
 GLIB_LIBS
 LIBOIL_CFLAGS
 LIBOIL_LIBS
+USE_LIBOIL_TRUE
+USE_LIBOIL_FALSE
 GST_CFLAGS
 GST_LIBS
 GST_TOOLS_DIR
@@ -1708,6 +1710,7 @@ Optional Features:
   --disable-external           disable building of plug-ins with external deps
   --enable-experimental        enable building of experimental plug-ins
   --enable-gtk-doc        use gtk-doc to build documentation default=no
+  --disable-liboil             disable liboil usage in some plugins
   --disable-asfdemux      disable dependency-less asfdemux plugin
   --disable-dvdlpcmdec    disable dependency-less dvdlpcmdec plugin
   --disable-dvdsub        disable dependency-less dvdsub plugin
@@ -4950,13 +4953,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4953: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4956: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4956: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4959: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4959: output\"" >&5)
+  (eval echo "\"\$as_me:4962: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5554,7 +5557,7 @@ if test "${lt_cv_ar_interface+set}" = set; then
 else
   lt_cv_ar_interface="ar"
   printf "$lt_simple_compile_test_code" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5557: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5560: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
   (eval "$AR -NOLOGO -OUT:conftest.lib conftest.$ac_objext" &>conftest.err)
@@ -6172,7 +6175,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6175 "configure"' > conftest.$ac_ext
+  echo '#line 6178 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7712,11 +7715,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7715: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7718: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7719: \$? = $ac_status" >&5
+   echo "$as_me:7722: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8036,11 +8039,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8039: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8042: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8043: \$? = $ac_status" >&5
+   echo "$as_me:8046: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8141,11 +8144,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8144: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8147: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8148: \$? = $ac_status" >&5
+   echo "$as_me:8151: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8196,11 +8199,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8199: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8202: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8203: \$? = $ac_status" >&5
+   echo "$as_me:8206: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11033,7 +11036,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11036 "configure"
+#line 11039 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11133,7 +11136,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11136 "configure"
+#line 11139 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18339,11 +18342,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18342: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18345: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18346: \$? = $ac_status" >&5
+   echo "$as_me:18349: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18438,11 +18441,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18441: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18444: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18445: \$? = $ac_status" >&5
+   echo "$as_me:18448: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18490,11 +18493,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18493: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18496: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18497: \$? = $ac_status" >&5
+   echo "$as_me:18500: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23642,6 +23645,49 @@ echo "$as_me: error: This package requires GLib >= $GLIB_REQ to compile." >&2;}
 
 
 
+echo
+{ echo "$as_me:$LINENO: *** checking feature: liboil usage in some plugins ***" >&5
+echo "$as_me: *** checking feature: liboil usage in some plugins ***" >&6;}
+if test "x" != "x"
+then
+  { echo "$as_me:$LINENO: *** for plug-ins:  ***" >&5
+echo "$as_me: *** for plug-ins:  ***" >&6;}
+fi
+NOUSE=
+if test "x$USE_LIBOIL" = "xno"; then
+  NOUSE="yes"
+fi
+# Check whether --enable-liboil was given.
+if test "${enable_liboil+set}" = set; then
+  enableval=$enable_liboil;  case "${enableval}" in
+      yes) USE_LIBOIL=yes;;
+      no) USE_LIBOIL=no;;
+      *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-liboil" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-liboil" >&2;}
+   { (exit 1); exit 1; }; } ;;
+    esac
+else
+   USE_LIBOIL=yes
+fi
+
+if test "x$NOUSE" = "xyes"; then
+  USE_LIBOIL="no"
+  { echo "$as_me:$LINENO: WARNING: ***  pre-configured not to be built" >&5
+echo "$as_me: WARNING: ***  pre-configured not to be built" >&2;}
+fi
+NOUSE=
+
+
+if test x$USE_LIBOIL = xyes; then
+
+  gst_check_save_LIBS=$LIBS
+  gst_check_save_LDFLAGS=$LDFLAGS
+  gst_check_save_CFLAGS=$CFLAGS
+  gst_check_save_CPPFLAGS=$CPPFLAGS
+  gst_check_save_CXXFLAGS=$CXXFLAGS
+
+  HAVE_LIBOIL=no
+
 
 pkg_failed=no
 { echo "$as_me:$LINENO: checking for LIBOIL" >&5
@@ -23652,12 +23698,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_LIBOIL_CFLAGS="$LIBOIL_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liboil-0.3 >= 0.3.8\"") >&5
-  ($PKG_CONFIG --exists --print-errors "liboil-0.3 >= 0.3.8") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liboil-0.3 >= 0.3.14\"") >&5
+  ($PKG_CONFIG --exists --print-errors "liboil-0.3 >= 0.3.14") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_LIBOIL_CFLAGS=`$PKG_CONFIG --cflags "liboil-0.3 >= 0.3.8" 2>/dev/null`
+  pkg_cv_LIBOIL_CFLAGS=`$PKG_CONFIG --cflags "liboil-0.3 >= 0.3.14" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -23670,12 +23716,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_LIBOIL_LIBS="$LIBOIL_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liboil-0.3 >= 0.3.8\"") >&5
-  ($PKG_CONFIG --exists --print-errors "liboil-0.3 >= 0.3.8") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"liboil-0.3 >= 0.3.14\"") >&5
+  ($PKG_CONFIG --exists --print-errors "liboil-0.3 >= 0.3.14") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_LIBOIL_LIBS=`$PKG_CONFIG --libs "liboil-0.3 >= 0.3.8" 2>/dev/null`
+  pkg_cv_LIBOIL_LIBS=`$PKG_CONFIG --libs "liboil-0.3 >= 0.3.14" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -23685,7 +23731,7 @@ else
 fi
 
 if test $pkg_failed = yes; then
-	LIBOIL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "liboil-0.3 >= 0.3.8"`
+	LIBOIL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "liboil-0.3 >= 0.3.14"`
 	# Put the nasty error message in config.log where it belongs
 	echo "$LIBOIL_PKG_ERRORS" 1>&5
 
@@ -23699,11 +23745,56 @@ else
 echo "${ECHO_T}yes" >&6; }
 	HAVE_LIBOIL=yes
 fi
-if test "x$HAVE_LIBOIL" != "xyes"; then
-  { { echo "$as_me:$LINENO: error: liboil-0.3.8 or later is required" >&5
-echo "$as_me: error: liboil-0.3.8 or later is required" >&2;}
-   { (exit 1); exit 1; }; }
+  if test "x$HAVE_LIBOIL" = "xyes"; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBOIL 1
+_ACEOF
+
+  fi
+
+
+  LIBS=$gst_check_save_LIBS
+  LDFLAGS=$gst_check_save_LDFLAGS
+  CFLAGS=$gst_check_save_CFLAGS
+  CPPFLAGS=$gst_check_save_CPPFLAGS
+  CXXFLAGS=$gst_check_save_CXXFLAGS
+
+    if test x$HAVE_LIBOIL = xno; then
+    USE_LIBOIL=no
+  else
+    :
+  fi
 fi
+if test x$USE_LIBOIL = xyes; then
+  :
+  if test "x" != "x"; then
+    GST_PLUGINS_YES="\t\n$GST_PLUGINS_YES"
+  fi
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBOIL
+_ACEOF
+
+else
+  :
+  if test "x" != "x"; then
+    GST_PLUGINS_NO="\t\n$GST_PLUGINS_NO"
+  fi
+  :
+fi
+
+
+if test x$USE_LIBOIL = xyes; then
+  USE_LIBOIL_TRUE=
+  USE_LIBOIL_FALSE='#'
+else
+  USE_LIBOIL_TRUE='#'
+  USE_LIBOIL_FALSE=
+fi
+
+
+
 
 
 
@@ -29556,6 +29647,13 @@ echo "$as_me: error: conditional \"ENABLE_PLUGIN_DOCS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${USE_LIBOIL_TRUE}" && test -z "${USE_LIBOIL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"USE_LIBOIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"USE_LIBOIL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_GST_CHECK_TRUE}" && test -z "${HAVE_GST_CHECK_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_GST_CHECK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -31029,6 +31127,8 @@ GLIB_CFLAGS!$GLIB_CFLAGS$ac_delim
 GLIB_LIBS!$GLIB_LIBS$ac_delim
 LIBOIL_CFLAGS!$LIBOIL_CFLAGS$ac_delim
 LIBOIL_LIBS!$LIBOIL_LIBS$ac_delim
+USE_LIBOIL_TRUE!$USE_LIBOIL_TRUE$ac_delim
+USE_LIBOIL_FALSE!$USE_LIBOIL_FALSE$ac_delim
 GST_CFLAGS!$GST_CFLAGS$ac_delim
 GST_LIBS!$GST_LIBS$ac_delim
 GST_TOOLS_DIR!$GST_TOOLS_DIR$ac_delim
@@ -31104,8 +31204,6 @@ USE_ID3TAG_TRUE!$USE_ID3TAG_TRUE$ac_delim
 USE_ID3TAG_FALSE!$USE_ID3TAG_FALSE$ac_delim
 MAD_CFLAGS!$MAD_CFLAGS$ac_delim
 MAD_LIBS!$MAD_LIBS$ac_delim
-USE_MAD_TRUE!$USE_MAD_TRUE$ac_delim
-USE_MAD_FALSE!$USE_MAD_FALSE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -31147,6 +31245,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+USE_MAD_TRUE!$USE_MAD_TRUE$ac_delim
+USE_MAD_FALSE!$USE_MAD_FALSE$ac_delim
 MPEG2DEC_CFLAGS!$MPEG2DEC_CFLAGS$ac_delim
 MPEG2DEC_LIBS!$MPEG2DEC_LIBS$ac_delim
 USE_MPEG2DEC_TRUE!$USE_MPEG2DEC_TRUE$ac_delim
@@ -31166,7 +31266,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 17; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 19; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
