update gettext

diff --git a/gettext/gettext-tools/tests/lang-bash b/gettext/gettext-tools/tests/lang-bash
--- a/gettext/gettext-tools/tests/lang-bash
+++ b/gettext/gettext-tools/tests/lang-bash
@@ -4,6 +4,11 @@
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: bash 2.0 or newer.
 
+# This test fails on MacOS X 10.5 because its 'bash' command is built with
+# an included intl directory without iconv support; hence it produces wrong
+# output when accessing any .mo file not generated from a .po file in UTF-8
+# encoding.
+
 tmpfiles=""
 trap 'rm -fr $tmpfiles' 1 2 3 15
 
@@ -25,14 +30,16 @@ $echo $"'Your command, please?', asked the waiter."
 $echo "`eval_ngettext "a piece of cake" "\\$n pieces of cake" $n`"
 EOF
 
-tmpfiles="$tmpfiles prog.pot prog.err"
+tmpfiles="$tmpfiles prog.tmp prog.pot prog.err"
 : ${XGETTEXT=xgettext}
 LC_MESSAGES=C LC_ALL= \
-${XGETTEXT} -o prog.pot --omit-header --no-location prog.sh \
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.sh \
   >prog.err 2>&1
 result=$?
 cat prog.err | grep -v 'warning: the syntax \$"\.\.\." is deprecated due to security reasons'
 test $result = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 tmpfiles="$tmpfiles prog.ok"
 cat <<\EOF > prog.ok
@@ -67,9 +74,12 @@ msgstr[0] "un morceau de gateau"
 msgstr[1] "$n morceaux de gateau"
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
+tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
@@ -83,10 +93,10 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of bash version 2.0 or newer.
 (bash -c :) >/dev/null 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: bash not found"; rm -fr $tmpfiles; exit 77; }
 case `bash -c 'echo $BASH_VERSION'` in
   [2-9].*) ;;
-  *) rm -fr $tmpfiles; exit 77;;
+  *) echo "Skipping test: bash version too old"; rm -fr $tmpfiles; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
@@ -109,6 +119,11 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
   rm -fr $tmpfiles; exit 77
 fi
 
@@ -133,13 +148,19 @@ EOF
 if test $LOCALE_FR != none; then
   LANGUAGE= LC_ALL=$LOCALE_FR bash ./prog.sh 2 > prog.out || exit 1
   : ${DIFF=diff}
-  ${DIFF} prog.nok prog.out > /dev/null && { rm -fr $tmpfiles; exit 77; }
+  ${DIFF} prog.nok prog.out > /dev/null && {
+    echo "Skipping test: bash is built without i18n support"
+    rm -fr $tmpfiles; exit 77
+  }
   ${DIFF} prog.ok prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
   LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 bash ./prog.sh 2 > prog.out || exit 1
   : ${DIFF=diff}
-  ${DIFF} prog.nok prog.out > /dev/null && { rm -fr $tmpfiles; exit 77; }
+  ${DIFF} prog.nok prog.out > /dev/null && {
+    echo "Skipping test: bash is built without i18n support"
+    rm -fr $tmpfiles; exit 77
+  }
   ${DIFF} prog.oku prog.out || exit 1
 fi
 
diff --git a/gettext/gettext-tools/tests/lang-clisp b/gettext/gettext-tools/tests/lang-clisp
--- a/gettext/gettext-tools/tests/lang-clisp
+++ b/gettext/gettext-tools/tests/lang-clisp
@@ -21,9 +21,12 @@ cat <<\EOF > prog.lisp
 (format t "~A~%" (format nil (gettext "~A is replaced by ~A.") "FF" "EUR"))
 EOF
 
-tmpfiles="$tmpfiles prog.pot"
+tmpfiles="$tmpfiles prog.tmp prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --no-location prog.lisp
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.lisp
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
@@ -67,9 +70,12 @@ msgid "~A is replaced by ~A."
 msgstr "~1@*~A remplace ~0@*~A."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
+tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
@@ -85,16 +91,18 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 # Use clisp for the comparison of the version numbers; neither 'expr' nor 'bc'
 # can deal with floating-point numbers.
 (clisp --version) >/dev/null 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: clisp not found"; rm -fr $tmpfiles; exit 77; }
 version=`clisp --version | sed -n -e 1p | sed -e 's/^[^0-9]*//'`
 case $version in
   19* | 20*) # older than 2.25
-    rm -fr $tmpfiles; exit 77;;
+    echo "Skipping test: clisp version too old"; rm -fr $tmpfiles; exit 77;;
 esac
 version=`echo $version | sed -e 's/^\([0-9]*\.[0-9]*\).*/\1/'`
 clisp -norc -x "(sys::exit #+GETTEXT (not (>= $version 2.28)) #-GETTEXT t)" \
       >/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: clisp was built without gettext support"
+       rm -fr $tmpfiles; exit 77
+     }
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
@@ -116,6 +124,11 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
   rm -fr $tmpfiles; exit 77
 fi
 
@@ -135,11 +148,13 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR clisp prog.lisp 2 > prog.out || exit 1
+  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR clisp prog.lisp 2 > prog.tmp || exit 1
+  LC_ALL=C tr -d '\r' < prog.tmp > prog.out || exit 1
   ${DIFF} prog.ok prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 clisp prog.lisp 2 > prog.out || exit 1
+  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 clisp prog.lisp 2 > prog.tmp || exit 1
+  LC_ALL=C tr -d '\r' < prog.tmp > prog.out || exit 1
   ${DIFF} prog.oku prog.out || exit 1
 fi
 
diff --git a/gettext/gettext-tools/tests/lang-gawk b/gettext/gettext-tools/tests/lang-gawk
--- a/gettext/gettext-tools/tests/lang-gawk
+++ b/gettext/gettext-tools/tests/lang-gawk
@@ -25,9 +25,12 @@ BEGIN {
 }
 EOF
 
-tmpfiles="$tmpfiles prog.pot"
+tmpfiles="$tmpfiles prog.tmp prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --no-location prog.awk
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.awk
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
@@ -71,9 +74,12 @@ msgid "%s is replaced by %s."
 msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
+tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
@@ -85,12 +91,12 @@ test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 : ${MSGFMT=msgfmt}
 ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
-# Test for presence of gawk version 3.1.1 or newer.
+# Test for presence of gawk version 3.1.3 or newer, excluding version 3.1.5.
 (gawk --version) >/dev/null 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: gawk not found"; rm -fr $tmpfiles; exit 77; }
 case `gawk --version 2>&1 | sed -e 's/^[^0-9]*//'` in
-  0.* | 1.* | 2.* | 3.0* | 3.1.0*)
-    rm -fr $tmpfiles; exit 77;;
+  0.* | 1.* | 2.* | 3.0* | 3.1.0* | 3.1.1* | 3.1.2* | 3.1.5*)
+    echo "Skipping test: gawk version too old"; rm -fr $tmpfiles; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
@@ -113,6 +119,11 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
   rm -fr $tmpfiles; exit 77
 fi
 
@@ -121,11 +132,17 @@ fi
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
   LANGUAGE= LC_ALL=$LOCALE_FR gawk --version | grep logiciel > /dev/null
-  test $? = 0 || { rm -fr $tmpfiles; exit 77; }
+  test $? = 0 || {
+    echo "Skipping test: gawk was built without i18n support"
+    rm -fr $tmpfiles; exit 77
+  }
 fi
 if test $LOCALE_FR_UTF8 != none; then
   LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 gawk --version | grep logiciel > /dev/null
-  test $? = 0 || { rm -fr $tmpfiles; exit 77; }
+  test $? = 0 || {
+    echo "Skipping test: gawk was built without i18n support"
+    rm -fr $tmpfiles; exit 77
+  }
 fi
 
 tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
diff --git a/gettext/gettext-tools/tests/lang-java b/gettext/gettext-tools/tests/lang-java
--- a/gettext/gettext-tools/tests/lang-java
+++ b/gettext/gettext-tools/tests/lang-java
@@ -11,7 +11,18 @@ tmpfiles=""
 trap 'rm -fr $tmpfiles' 1 2 3 15
 
 # Test whether we can build and test Java programs.
-test "${TESTJAVA}" = yes || exit 77
+test "${JAVA_CHOICE}" != no || {
+  echo "Skipping test: configured with --disable-java"
+  exit 77
+}
+test "${BUILDJAVA}" = yes || {
+  echo "Skipping test: Java compiler or jar not found"
+  exit 77
+}
+test "${TESTJAVA}" = yes || {
+  echo "Skipping test: Java engine not found"
+  exit 77
+}
 
 tmpfiles="$tmpfiles Program.java"
 cat <<\EOF > Program.java
@@ -27,24 +38,13 @@ public class Program {
     Locale.setDefault(new Locale("fr","FR"));
 EOF
 case "$host_os" in
-  darwin[56]*)
-cat <<\EOF >> Program.java
-    // Some systems (like MacOS X) don't set System.out's character encoding
-    // to ISO-8859-1, which is what we need for comparison purposes.
-    try {
-      System.setOut(new PrintStream(new FileOutputStream(FileDescriptor.out),
-                                    true, "ISO-8859-1"));
-    } catch (UnsupportedEncodingException e) {
-    }
-EOF
-    ;;
   darwin*)
 cat <<\EOF >> Program.java
     // Some systems (like MacOS X) don't set System.out's character encoding
-    // to UTF-8, which is what we need for comparison purposes.
+    // according to LC_ALL, which is what we need for comparison purposes.
     try {
       System.setOut(new PrintStream(new FileOutputStream(FileDescriptor.out),
-                                    true, "UTF-8"));
+                                    true, args[1]));
     } catch (UnsupportedEncodingException e) {
     }
 EOF
@@ -56,17 +56,23 @@ cat <<\EOF >> Program.java
     System.out.println(GettextResource.gettext(catalog,"'Your command, please?', asked the waiter."));
     System.out.println(MessageFormat.format(GettextResource.ngettext(catalog,"a piece of cake","{0,number} pieces of cake",n), new Object[] { new Integer(n) }));
     System.out.println(MessageFormat.format(GettextResource.gettext(catalog,"{0} is replaced by {1}."), new Object[] { "FF", "EUR" }));
+    System.out.println(MessageFormat.format(GettextResource.npgettext(catalog,"++","a piece of cake","{0,number} pieces of cake",n), new Object[] { new Integer(n) }));
+    System.out.println(MessageFormat.format(GettextResource.pgettext(catalog,"++","{0} is replaced by {1}."), new Object[] { "FF", "EUR" }));
   }
 }
 EOF
 
-tmpfiles="$tmpfiles Program.class"
-: ${JAVACOMP="/bin/sh ../lib/javacomp.sh"}
-CLASSPATH=../../gettext-runtime/intl-java/libintl.jar ${JAVACOMP} -d . Program.java || exit 1
+tmpfiles="$tmpfiles Program.class prog.err"
+: ${JAVACOMP="/bin/sh ../javacomp.sh"}
+CLASSPATH=../../gettext-runtime/intl-java/libintl.jar ${JAVACOMP} -d . Program.java 2>prog.err \
+  || { cat prog.err 1>&2; exit 1; }
 
-tmpfiles="$tmpfiles prog.pot"
+tmpfiles="$tmpfiles prog.tmp prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --no-location Program.java
+${XGETTEXT} -o prog.tmp --omit-header --no-location Program.java
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
@@ -80,6 +86,18 @@ msgstr[0] ""
 msgstr[1] ""
 
 #, java-format
+msgid "{0} is replaced by {1}."
+msgstr ""
+
+#, java-format
+msgctxt "++"
+msgid "a piece of cake"
+msgid_plural "{0,number} pieces of cake"
+msgstr[0] ""
+msgstr[1] ""
+
+#, java-format
+msgctxt "++"
 msgid "{0} is replaced by {1}."
 msgstr ""
 EOF
@@ -108,11 +126,28 @@ msgstr[1] "{0,number} morceaux de gateau"
 #, java-format
 msgid "{0} is replaced by {1}."
 msgstr "{1} remplace {0}."
+
+# Euphemistic formulation.
+#, java-format
+msgctxt "++"
+msgid "a piece of cake"
+msgid_plural "{0,number} pieces of cake"
+msgstr[0] "un morceau de gateau succulent"
+msgstr[1] "{0,number} morceaux de gateau succulent"
+
+# Euphemistic formulation.
+#, java-format
+msgctxt "++"
+msgid "{0} is replaced by {1}."
+msgstr "Le nouveau {1} remplace le vieux {0}."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
+tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
@@ -141,6 +176,11 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
   rm -fr $tmpfiles; exit 77
 fi
 
@@ -150,22 +190,26 @@ cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
 2 morceaux de gateau
 EUR remplace FF.
+2 morceaux de gateau succulent
+Le nouveau EUR remplace le vieux FF.
 EOF
 cat <<\EOF > prog.oku
 Â«Votre commande, s'il vous plaitÂ», dit le garÃ§on.
 2 morceaux de gateau
 EUR remplace FF.
+2 morceaux de gateau succulent
+Le nouveau EUR remplace le vieux FF.
 EOF
 
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
-: ${JAVAEXEC="/bin/sh ../lib/javaexec.sh"}
+: ${JAVAEXEC="/bin/sh ../javaexec.sh"}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR CLASSPATH=.:../../gettext-runtime/intl-java/libintl.jar ${JAVAEXEC} Program 2 > prog.out || exit 1
+  LANGUAGE= LC_ALL=$LOCALE_FR CLASSPATH=.:../../gettext-runtime/intl-java/libintl.jar ${JAVAEXEC} Program 2 ISO-8859-1 > prog.out || exit 1
   ${DIFF} prog.ok prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 CLASSPATH=.:../../gettext-runtime/intl-java/libintl.jar ${JAVAEXEC} Program 2 > prog.out || exit 1
+  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 CLASSPATH=.:../../gettext-runtime/intl-java/libintl.jar ${JAVAEXEC} Program 2 UTF-8 > prog.out || exit 1
   ${DIFF} prog.oku prog.out || exit 1
 fi
 
diff --git a/gettext/gettext-tools/tests/lang-librep b/gettext/gettext-tools/tests/lang-librep
--- a/gettext/gettext-tools/tests/lang-librep
+++ b/gettext/gettext-tools/tests/lang-librep
@@ -20,9 +20,12 @@ cat <<\EOF > prog.jl
         (format nil (_ "%s is replaced by %s.") "FF" "EUR"))
 EOF
 
-tmpfiles="$tmpfiles prog.pot"
+tmpfiles="$tmpfiles prog.tmp prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --no-location prog.jl
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.jl
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
@@ -53,9 +56,12 @@ msgid "%s is replaced by %s."
 msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
+tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
@@ -69,10 +75,10 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of rep version 0.15.3 or newer.
 (rep --version) >/dev/null 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: rep not found"; rm -fr $tmpfiles; exit 77; }
 case `rep --version | sed -e 's/^[^0-9]*//'` in
   0.[0-9] | 0.1[0-5] | 0.[0-9].* | 0.1[0-4].* | 0.15.[0-2] )
-    rm -fr $tmpfiles; exit 77;;
+    echo "Skipping test: rep version too old"; rm -fr $tmpfiles; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
@@ -95,6 +101,11 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
   rm -fr $tmpfiles; exit 77
 fi
 
diff --git a/gettext/gettext-tools/tests/lang-pascal b/gettext/gettext-tools/tests/lang-pascal
--- a/gettext/gettext-tools/tests/lang-pascal
+++ b/gettext/gettext-tools/tests/lang-pascal
@@ -6,7 +6,7 @@
 # Note: This test fails with fpk 1.0.10 when an UTF-8 locale is present,
 # because fpk ignores the locale's encoding. It supports only unibyte locales.
 # This here is a quick workaround:
-LOCALE_FR_UTF8=none
+UTF8_LOCALE_UNSUPPORTED=yes
 
 tmpfiles=""
 trap 'rm -fr $tmpfiles' 1 2 3 15
@@ -30,11 +30,19 @@ end.
 EOF
 
 tmpfiles="$tmpfiles prog.o prog.rst prog"
-(ppc386 prog.pp) >/dev/null 2>&1 || { rm -fr $tmpfiles; exit 77; }
+(ppc386 prog.pp) >/dev/null 2>&1 ||
+(ppcx64 prog.pp) >/dev/null 2>&1 ||
+{
+  echo "Skipping test: Pascal compiler ppc386 or ppcx64 not found"
+  rm -fr $tmpfiles; exit 77
+}
 
-tmpfiles="$tmpfiles prog.pot"
+tmpfiles="$tmpfiles prog.tmp prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --add-location prog.rst
+${XGETTEXT} -o prog.tmp --omit-header --add-location prog.rst
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
@@ -67,9 +75,12 @@ msgid "%s is replaced by %s."
 msgstr "%1:s remplace %0:s."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
+tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
@@ -99,13 +110,29 @@ if test $LOCALE_FR != none; then
   : ${DIFF=diff}
   ${DIFF} prog.ok prog.out || exit 1
 fi
-if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL= LC_MESSAGES= LC_CTYPE= LANG=$LOCALE_FR_UTF8 ./prog > prog.out || exit 1
-  : ${DIFF=diff}
-  ${DIFF} prog.oku prog.out || exit 1
-fi
-if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
-  rm -fr $tmpfiles; exit 77
+if test -z "$UTF8_LOCALE_UNSUPPORTED"; then
+  if test $LOCALE_FR_UTF8 != none; then
+    LANGUAGE= LC_ALL= LC_MESSAGES= LC_CTYPE= LANG=$LOCALE_FR_UTF8 ./prog > prog.out || exit 1
+    : ${DIFF=diff}
+    ${DIFF} prog.oku prog.out || exit 1
+  fi
+  if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
+    if test -f /usr/bin/localedef; then
+      echo "Skipping test: no french locale is installed"
+    else
+      echo "Skipping test: no french locale is supported"
+    fi
+    rm -fr $tmpfiles; exit 77
+  fi
+else
+  if test $LOCALE_FR = none; then
+    if test -f /usr/bin/localedef; then
+      echo "Skipping test: no traditional french locale is installed"
+    else
+      echo "Skipping test: no traditional french locale is supported"
+    fi
+    rm -fr $tmpfiles; exit 77
+  fi
 fi
 
 rm -fr $tmpfiles
diff --git a/gettext/gettext-tools/tests/lang-php b/gettext/gettext-tools/tests/lang-php
--- a/gettext/gettext-tools/tests/lang-php
+++ b/gettext/gettext-tools/tests/lang-php
@@ -9,20 +9,23 @@ trap 'rm -fr $tmpfiles' 1 2 3 15
 
 tmpfiles="$tmpfiles prog.php"
 cat <<\EOF > prog.php
-<?
+<?php
   setlocale (LC_ALL, "");
   textdomain ("prog");
   bindtextdomain ("prog", ".");
   echo _("'Your command, please?', asked the waiter.");
   echo "\n";
-  echo printf(_("%s is replaced by %s."), "FF", "EUR");
+  printf(_("%s is replaced by %s."), "FF", "EUR");
   echo "\n";
 ?>
 EOF
 
-tmpfiles="$tmpfiles prog.pot"
+tmpfiles="$tmpfiles prog.tmp prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --no-location prog.php
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.php
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
@@ -51,9 +54,12 @@ msgid "%s is replaced by %s."
 msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
+tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
+test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
@@ -65,11 +71,18 @@ test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 : ${MSGFMT=msgfmt}
 ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
-# Test for presence of php version 4.0 or newer.
-case `(php -v) 2>/dev/null` in
+# Test for presence of php version 4.0 or newer with gettext support.
+(php -v) >/dev/null 2>/dev/null
+test $? -le 1 \
+  || { echo "Skipping test: php not found"; rm -fr $tmpfiles; exit 77; }
+case `php -v | sed -n -e 1p | sed -e 's/^[^0-9]*//'` in
   [4-9].*) ;;
-  *) rm -fr $tmpfiles; exit 77;;
+  *) echo "Skipping test: php version too old"; rm -fr $tmpfiles; exit 77;;
 esac
+{ php -m | grep '^gettext$' >/dev/null; } \
+  || { echo "Skipping test: php was built without gettext support"
+       rm -fr $tmpfiles; exit 77
+     }
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
@@ -91,6 +104,11 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
   rm -fr $tmpfiles; exit 77
 fi
 
