update gettext

diff --git a/gettext/gettext-tools/tests/lang-bash b/gettext/gettext-tools/tests/lang-bash
--- a/gettext/gettext-tools/tests/lang-bash
+++ b/gettext/gettext-tools/tests/lang-bash
@@ -1,14 +1,16 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src ${top_srcdir=..}/../gettext-runtime/src
 
 # Test of gettext facilities in the bash language.
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: bash 2.0 or newer.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
+# This test fails on MacOS X 10.5 because its 'bash' command is built with
+# an included intl directory without iconv support; hence it produces wrong
+# output when accessing any .mo file not generated from a .po file in UTF-8
+# encoding.
 
-tmpfiles="$tmpfiles prog.sh"
-cat <<\EOF > prog.sh
+cat <<\EOF > prog.bash
 #! /bin/bash
 
 n=$1
@@ -25,16 +27,15 @@ $echo $"'Your command, please?', asked the waiter."
 $echo "`eval_ngettext "a piece of cake" "\\$n pieces of cake" $n`"
 EOF
 
-tmpfiles="$tmpfiles prog.pot prog.err"
 : ${XGETTEXT=xgettext}
 LC_MESSAGES=C LC_ALL= \
-${XGETTEXT} -o prog.pot --omit-header --no-location prog.sh \
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.bash \
   >prog.err 2>&1
 result=$?
 cat prog.err | grep -v 'warning: the syntax \$"\.\.\." is deprecated due to security reasons'
-test $result = 0 || { rm -fr $tmpfiles; exit 1; }
+test $result = 0 || { exit 1; }
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
 cat <<\EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -49,7 +50,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} prog.ok prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
 cat <<\EOF > fr.po
 msgid ""
 msgstr ""
@@ -67,14 +67,13 @@ msgstr[0] "un morceau de gateau"
 msgstr[1] "$n morceaux de gateau"
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
@@ -83,17 +82,17 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of bash version 2.0 or newer.
 (bash -c :) >/dev/null 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: bash not found"; exit 77; }
 case `bash -c 'echo $BASH_VERSION'` in
   [2-9].*) ;;
-  *) rm -fr $tmpfiles; exit 77;;
+  *) echo "Skipping test: bash version too old"; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LC_ALL=$LOCALE_FR ./testlocale
+  LC_ALL=$LOCALE_FR ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
@@ -101,7 +100,7 @@ if test $LOCALE_FR != none; then
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LC_ALL=$LOCALE_FR_UTF8 ./testlocale
+  LC_ALL=$LOCALE_FR_UTF8 ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
@@ -109,10 +108,27 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
-  rm -fr $tmpfiles; exit 77
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
+  exit 77
 fi
 
-tmpfiles="$tmpfiles prog.nok prog.ok prog.oku prog.out"
+case "$host_os" in
+  darwin*)
+    if test $LOCALE_FR != none; then
+      LC_ALL=$LOCALE_FR bash --help \
+        | grep '^Utilisation' > /dev/null 2>&1 || exit 77
+    fi
+    if test $LOCALE_FR_UTF8 != none; then
+      LC_ALL=$LOCALE_FR_UTF8 bash --help \
+        | grep '^Utilisation' > /dev/null 2>&1 || exit 77
+    fi
+  ;;
+esac
+
 # Expected result when bash is built without i18n support.
 cat <<\EOF > prog.nok
 'Your command, please?', asked the waiter.
@@ -131,18 +147,24 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR bash ./prog.sh 2 > prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR
+  LANGUAGE= LC_ALL=$LOCALE_FR bash ./prog.bash 2 > prog.out || exit 1
   : ${DIFF=diff}
-  ${DIFF} prog.nok prog.out > /dev/null && { rm -fr $tmpfiles; exit 77; }
+  ${DIFF} prog.nok prog.out > /dev/null && {
+    echo "Skipping test: bash is built without i18n support"
+    exit 77
+  }
   ${DIFF} prog.ok prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 bash ./prog.sh 2 > prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR_UTF8
+  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 bash ./prog.bash 2 > prog.out || exit 1
   : ${DIFF=diff}
-  ${DIFF} prog.nok prog.out > /dev/null && { rm -fr $tmpfiles; exit 77; }
+  ${DIFF} prog.nok prog.out > /dev/null && {
+    echo "Skipping test: bash is built without i18n support"
+    exit 77
+  }
   ${DIFF} prog.oku prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext/gettext-tools/tests/lang-clisp b/gettext/gettext-tools/tests/lang-clisp
--- a/gettext/gettext-tools/tests/lang-clisp
+++ b/gettext/gettext-tools/tests/lang-clisp
@@ -1,13 +1,10 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the CLISP language.
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: clisp.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.lisp"
 cat <<\EOF > prog.lisp
 (setf (textdomain) "prog")
 (setf (textdomaindir "prog") "./")
@@ -21,11 +18,10 @@ cat <<\EOF > prog.lisp
 (format t "~A~%" (format nil (gettext "~A is replaced by ~A.") "FF" "EUR"))
 EOF
 
-tmpfiles="$tmpfiles prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --no-location prog.lisp
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.lisp || exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -44,7 +40,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} prog.ok prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
 cat <<\EOF > fr.po
 msgid ""
 msgstr ""
@@ -67,14 +62,13 @@ msgid "~A is replaced by ~A."
 msgstr "~1@*~A remplace ~0@*~A."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
@@ -85,22 +79,24 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 # Use clisp for the comparison of the version numbers; neither 'expr' nor 'bc'
 # can deal with floating-point numbers.
 (clisp --version) >/dev/null 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: clisp not found"; exit 77; }
 version=`clisp --version | sed -n -e 1p | sed -e 's/^[^0-9]*//'`
 case $version in
   19* | 20*) # older than 2.25
-    rm -fr $tmpfiles; exit 77;;
+    echo "Skipping test: clisp version too old"; exit 77;;
 esac
 version=`echo $version | sed -e 's/^\([0-9]*\.[0-9]*\).*/\1/'`
 clisp -norc -x "(sys::exit #+GETTEXT (not (>= $version 2.28)) #-GETTEXT t)" \
       >/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: clisp was built without gettext support"
+       exit 77
+     }
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LC_ALL=$LOCALE_FR ./testlocale
+  LC_ALL=$LOCALE_FR ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
@@ -108,7 +104,7 @@ if test $LOCALE_FR != none; then
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LC_ALL=$LOCALE_FR_UTF8 ./testlocale
+  LC_ALL=$LOCALE_FR_UTF8 ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
@@ -116,10 +112,14 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
-  rm -fr $tmpfiles; exit 77
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
+  exit 77
 fi
 
-tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
 : ${DIFF=diff}
 cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -135,14 +135,16 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR clisp prog.lisp 2 > prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR
+  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR clisp prog.lisp 2 > prog.tmp || exit 1
+  LC_ALL=C tr -d '\r' < prog.tmp > prog.out || exit 1
   ${DIFF} prog.ok prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 clisp prog.lisp 2 > prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR_UTF8
+  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 clisp prog.lisp 2 > prog.tmp || exit 1
+  LC_ALL=C tr -d '\r' < prog.tmp > prog.out || exit 1
   ${DIFF} prog.oku prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext/gettext-tools/tests/lang-gawk b/gettext/gettext-tools/tests/lang-gawk
--- a/gettext/gettext-tools/tests/lang-gawk
+++ b/gettext/gettext-tools/tests/lang-gawk
@@ -1,4 +1,5 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the GNU awk language.
 # Assumes an fr_FR locale is installed.
@@ -8,10 +9,6 @@
 # but not in the fr_FR.UTF-8 locale. Probably because in the fr_FR locale,
 # nl_langinfo(CODESET) returns "".
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.awk"
 cat <<\EOF > prog.awk
 BEGIN {
   TEXTDOMAIN = "prog"
@@ -25,11 +22,10 @@ BEGIN {
 }
 EOF
 
-tmpfiles="$tmpfiles prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --no-location prog.awk
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.awk || exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -48,7 +44,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} prog.ok prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
 cat <<\EOF > fr.po
 msgid ""
 msgstr ""
@@ -71,33 +66,32 @@ msgid "%s is replaced by %s."
 msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
 ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
-# Test for presence of gawk version 3.1.1 or newer.
+# Test for presence of gawk version 3.1.3 or newer, excluding version 3.1.5.
 (gawk --version) >/dev/null 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: gawk not found"; exit 77; }
 case `gawk --version 2>&1 | sed -e 's/^[^0-9]*//'` in
-  0.* | 1.* | 2.* | 3.0* | 3.1.0*)
-    rm -fr $tmpfiles; exit 77;;
+  0.* | 1.* | 2.* | 3.0* | 3.1.0* | 3.1.1* | 3.1.2* | 3.1.5*)
+    echo "Skipping test: gawk version too old"; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LC_ALL=$LOCALE_FR ./testlocale
+  LC_ALL=$LOCALE_FR ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
@@ -105,7 +99,7 @@ if test $LOCALE_FR != none; then
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LC_ALL=$LOCALE_FR_UTF8 ./testlocale
+  LC_ALL=$LOCALE_FR_UTF8 ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
@@ -113,7 +107,12 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
-  rm -fr $tmpfiles; exit 77
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
+  exit 77
 fi
 
 # Test that gawk wasn't built with --disable-nls.
@@ -121,14 +120,19 @@ fi
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
   LANGUAGE= LC_ALL=$LOCALE_FR gawk --version | grep logiciel > /dev/null
-  test $? = 0 || { rm -fr $tmpfiles; exit 77; }
+  test $? = 0 || {
+    echo "Skipping test: gawk was built without i18n support"
+    exit 77
+  }
 fi
 if test $LOCALE_FR_UTF8 != none; then
   LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 gawk --version | grep logiciel > /dev/null
-  test $? = 0 || { rm -fr $tmpfiles; exit 77; }
+  test $? = 0 || {
+    echo "Skipping test: gawk was built without i18n support"
+    exit 77
+  }
 fi
 
-tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
 : ${DIFF=diff}
 cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -144,14 +148,14 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
+  prepare_locale_ fr $LOCALE_FR
   LANGUAGE= LC_ALL=$LOCALE_FR gawk -v n=2 -f prog.awk > prog.out || exit 1
   ${DIFF} prog.ok prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
+  prepare_locale_ fr $LOCALE_FR_UTF8
   LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 gawk -v n=2 -f prog.awk > prog.out || exit 1
   ${DIFF} prog.oku prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext/gettext-tools/tests/lang-guile b/gettext/gettext-tools/tests/lang-guile
--- a/gettext/gettext-tools/tests/lang-guile
+++ b/gettext/gettext-tools/tests/lang-guile
@@ -1,13 +1,10 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the guile implementation of Scheme.
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: guile.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.scm"
 cat <<\EOF > prog.scm
 (use-modules (ice-9 format))
 
@@ -24,11 +21,10 @@ cat <<\EOF > prog.scm
 (format #t "~A~%" (format #f (gettext "~A is replaced by ~A.") "FF" "EUR"))
 EOF
 
-tmpfiles="$tmpfiles prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --no-location prog.scm
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.scm || exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -47,7 +43,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} prog.ok prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
 cat <<\EOF > fr.po
 msgid ""
 msgstr ""
@@ -70,14 +65,13 @@ msgid "~A is replaced by ~A."
 msgstr "~1@*~A remplace ~0@*~A."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
@@ -86,17 +80,17 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of guile version 1.7 or newer.
 (guile --version) >/dev/null 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: guile not found"; exit 77; }
 case `guile --version | sed -e 1q | sed -e 's/^[^0-9]*//'` in
   0.* | 1.[0-6] | 1.[0-6].* )
-    rm -fr $tmpfiles; exit 77;;
+    echo "Skipping test: guile version too old"; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LC_ALL=$LOCALE_FR ./testlocale
+  LC_ALL=$LOCALE_FR ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
@@ -104,7 +98,7 @@ if test $LOCALE_FR != none; then
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LC_ALL=$LOCALE_FR_UTF8 ./testlocale
+  LC_ALL=$LOCALE_FR_UTF8 ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
@@ -112,10 +106,14 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
-  rm -fr $tmpfiles; exit 77
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
+  exit 77
 fi
 
-tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
 : ${DIFF=diff}
 cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -131,14 +129,16 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR guile -s prog.scm 2 > prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR
+  LANGUAGE= LC_ALL=$LOCALE_FR guile -s prog.scm 2 > prog.out 2>prog.err || { cat prog.err 1>&2; exit 1; }
+  grep -v '^;;;' prog.err 1>&2
   ${DIFF} prog.ok prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 guile -s prog.scm 2 > prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR_UTF8
+  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 guile -s prog.scm 2 > prog.out 2>prog.err || { cat prog.err 1>&2; exit 1; }
+  grep -v '^;;;' prog.err 1>&2
   ${DIFF} prog.oku prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext/gettext-tools/tests/lang-librep b/gettext/gettext-tools/tests/lang-librep
--- a/gettext/gettext-tools/tests/lang-librep
+++ b/gettext/gettext-tools/tests/lang-librep
@@ -1,13 +1,10 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the librep language.
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: librep.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.jl"
 cat <<\EOF > prog.jl
 (require 'rep.i18n.gettext)
 
@@ -20,11 +17,10 @@ cat <<\EOF > prog.jl
         (format nil (_ "%s is replaced by %s.") "FF" "EUR"))
 EOF
 
-tmpfiles="$tmpfiles prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --no-location prog.jl
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.jl || exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -37,7 +33,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} prog.ok prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
 cat <<\EOF > fr.po
 msgid ""
 msgstr ""
@@ -53,14 +48,13 @@ msgid "%s is replaced by %s."
 msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
@@ -69,17 +63,17 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of rep version 0.15.3 or newer.
 (rep --version) >/dev/null 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: rep not found"; exit 77; }
 case `rep --version | sed -e 's/^[^0-9]*//'` in
   0.[0-9] | 0.1[0-5] | 0.[0-9].* | 0.1[0-4].* | 0.15.[0-2] )
-    rm -fr $tmpfiles; exit 77;;
+    echo "Skipping test: rep version too old"; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LC_ALL=$LOCALE_FR ./testlocale
+  LC_ALL=$LOCALE_FR ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
@@ -87,7 +81,7 @@ if test $LOCALE_FR != none; then
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LC_ALL=$LOCALE_FR_UTF8 ./testlocale
+  LC_ALL=$LOCALE_FR_UTF8 ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
@@ -95,10 +89,14 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
-  rm -fr $tmpfiles; exit 77
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
+  exit 77
 fi
 
-tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
 : ${DIFF=diff}
 cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -112,14 +110,14 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
+  prepare_locale_ fr $LOCALE_FR
   LANGUAGE= LC_ALL=$LOCALE_FR rep --no-rc --batch prog.jl > prog.out || exit 1
   ${DIFF} prog.ok prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
+  prepare_locale_ fr $LOCALE_FR_UTF8
   LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 rep --no-rc --batch prog.jl > prog.out || exit 1
   ${DIFF} prog.oku prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext/gettext-tools/tests/lang-objc b/gettext/gettext-tools/tests/lang-objc
--- a/gettext/gettext-tools/tests/lang-objc
+++ b/gettext/gettext-tools/tests/lang-objc
@@ -1,14 +1,11 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the Objective C language.
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: gcc.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
 # Test whether an ObjectiveC compiler is found.
-tmpfiles="$tmpfiles hello.m hello.${OBJEXT} hello${EXEEXT}"
 cat <<\EOF > hello.m
 #include <stdio.h>
 #include <stdlib.h>
@@ -19,9 +16,10 @@ int main ()
 }
 EOF
 ${CC} ${CFLAGS} ${CPPFLAGS} ${LDFLAGS} -o hello hello.m 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: Objective C compiler not found"
+       exit 77
+     }
 
-tmpfiles="$tmpfiles prog.m"
 cat <<\EOF > prog.m
 #include "config.h"
 #include <libintl.h>
@@ -37,10 +35,8 @@ int main (int argc, char *argv[])
 
   xsetenv ("LC_ALL", argv[1], 1);
   if (setlocale (LC_ALL, "") == NULL)
-    {
-      fprintf (stderr, "Couldn't set locale.\n");
-      exit (77);
-    }
+    /* Couldn't set locale.  */
+    exit (77);
 
   textdomain ("prog");
   bindtextdomain ("prog", ".");
@@ -58,18 +54,22 @@ int main (int argc, char *argv[])
 }
 EOF
 
-# Variable needed by LTLIBINTL.
-top_builddir=..
+# Put the -I flags before ${CFLAGS} ${CPPFLAGS}, to make sure that libintl.h
+# is found in the build directory, regardless of -I options present in
+# ${CFLAGS} or ${CPPFLAGS}.
+${CC} -I../.. -I"$abs_top_srcdir"/gnulib-lib -I../../intl ${CFLAGS} \
+      ${CPPFLAGS} -c prog.m || exit 1
 
-tmpfiles="$tmpfiles prog.${OBJEXT} prog${EXEEXT}"
-${LIBTOOL} --quiet --mode=link ${CC} ${CFLAGS} ${CPPFLAGS} ${LDFLAGS} -o prog prog.m -I.. -I$top_srcdir/lib ../lib/libgettextlib.la -I../intl ${LTLIBINTL} \
-  || exit 1
+: ${CONFIG_SHELL=${SHELL-/bin/sh}}
+${CONFIG_SHELL} "$top_builddir"/libtool --quiet --tag=CC --mode=link \
+                ${CC} ${CFLAGS} -o prog prog.${OBJEXT} \
+                ../../gnulib-lib/libgettextlib.la ${LDFLAGS} ${LTLIBINTL} \
+		|| exit 1
 
-tmpfiles="$tmpfiles prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --no-location -k_ prog.m
+${XGETTEXT} -o prog.tmp --omit-header --no-location -k_ prog.m || exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
 #, c-format
 msgid "'Your command, please?', asked the waiter."
@@ -89,7 +89,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} prog.ok prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
 cat <<\EOF > fr.po
 msgid ""
 msgstr ""
@@ -113,21 +112,19 @@ msgid "%s is replaced by %s."
 msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
 ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
-tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
 : ${DIFF=diff}
 cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -143,6 +140,7 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
+  prepare_locale_ fr $LOCALE_FR
   LANGUAGE= ./prog $LOCALE_FR 2 > prog.out
   case $? in
     0) ${DIFF} prog.ok prog.out || exit 1;;
@@ -151,6 +149,7 @@ if test $LOCALE_FR != none; then
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
+  prepare_locale_ fr $LOCALE_FR_UTF8
   LANGUAGE= ./prog $LOCALE_FR_UTF8 2 > prog.out
   case $? in
     0) ${DIFF} prog.oku prog.out || exit 1;;
@@ -159,9 +158,12 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
-  rm -fr $tmpfiles; exit 77
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
+  exit 77
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext/gettext-tools/tests/lang-pascal b/gettext/gettext-tools/tests/lang-pascal
--- a/gettext/gettext-tools/tests/lang-pascal
+++ b/gettext/gettext-tools/tests/lang-pascal
@@ -1,4 +1,5 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the Object Pascal language.
 # Assumes the following packages are installed: fpk.
@@ -6,14 +7,10 @@
 # Note: This test fails with fpk 1.0.10 when an UTF-8 locale is present,
 # because fpk ignores the locale's encoding. It supports only unibyte locales.
 # This here is a quick workaround:
-LOCALE_FR_UTF8=none
+UTF8_LOCALE_UNSUPPORTED=yes
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.pp"
-cat <<\EOF > prog.pp
-program prog;
+cat <<\EOF > pascalprog.pp
+program pascalprog;
 {$mode delphi}
 
 uses gettext, sysutils;
@@ -23,71 +20,71 @@ resourcestring
   currencies = '%s is replaced by %s.';
 
 begin
-  translateresourcestrings('%s/LC_MESSAGES/prog.mo');
+  translateresourcestrings('%s/LC_MESSAGES/pascalprog.mo');
   writeln(question);
   writeln(format(currencies, ['FF', 'EUR']));
 end.
 EOF
 
-tmpfiles="$tmpfiles prog.o prog.rst prog"
-(ppc386 prog.pp) >/dev/null 2>&1 || { rm -fr $tmpfiles; exit 77; }
+(ppc386 pascalprog.pp) >/dev/null 2>&1 ||
+(ppcx64 pascalprog.pp) >/dev/null 2>&1 ||
+{
+  echo "Skipping test: Pascal compiler ppc386 or ppcx64 not found"
+  exit 77
+}
 
-tmpfiles="$tmpfiles prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --add-location prog.rst
+${XGETTEXT} -o pascalprog.tmp --omit-header --add-location pascalprog.rst || exit 1
+LC_ALL=C tr -d '\r' < pascalprog.tmp > pascalprog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
-cat <<EOF > prog.ok
-#: prog.question
+cat <<EOF > pascalprog.ok
+#: pascalprog.question
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
 
-#: prog.currencies
+#: pascalprog.currencies
 #, object-pascal-format
 msgid "%s is replaced by %s."
 msgstr ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} prog.ok prog.pot || exit 1
+${DIFF} pascalprog.ok pascalprog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
 cat <<\EOF > fr.po
 msgid ""
 msgstr "Content-Type: text/plain; charset=ISO-8859-1\n"
 
-#: prog.question
+#: pascalprog.question
 msgid "'Your command, please?', asked the waiter."
 msgstr "«Votre commande, s'il vous plait», dit le garçon."
 
 # Reverse the arguments.
-#: prog.currencies
+#: pascalprog.currencies
 #, object-pascal-format
 msgid "%s is replaced by %s."
 msgstr "%1:s remplace %0:s."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po pascalprog.pot || exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
+${MSGFMT} -o fr/LC_MESSAGES/pascalprog.mo fr.po
 
-tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
 : ${DIFF=diff}
-cat <<\EOF > prog.ok
+cat <<\EOF > pascalprog.ok
 «Votre commande, s'il vous plait», dit le garçon.
 EUR remplace FF.
 EOF
-cat <<\EOF > prog.oku
+cat <<\EOF > pascalprog.oku
 Â«Votre commande, s'il vous plaitÂ», dit le garÃ§on.
 EUR remplace FF.
 EOF
@@ -95,19 +92,35 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL= LC_MESSAGES= LC_CTYPE= LANG=$LOCALE_FR ./prog > prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR
+  LANGUAGE= LC_ALL= LC_MESSAGES= LC_CTYPE= LANG=$LOCALE_FR ./pascalprog > pascalprog.out || exit 1
   : ${DIFF=diff}
-  ${DIFF} prog.ok prog.out || exit 1
+  ${DIFF} pascalprog.ok pascalprog.out || exit 1
 fi
-if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL= LC_MESSAGES= LC_CTYPE= LANG=$LOCALE_FR_UTF8 ./prog > prog.out || exit 1
-  : ${DIFF=diff}
-  ${DIFF} prog.oku prog.out || exit 1
+if test -z "$UTF8_LOCALE_UNSUPPORTED"; then
+  if test $LOCALE_FR_UTF8 != none; then
+    prepare_locale_ fr $LOCALE_FR_UTF8
+    LANGUAGE= LC_ALL= LC_MESSAGES= LC_CTYPE= LANG=$LOCALE_FR_UTF8 ./pascalprog > pascalprog.out || exit 1
+    : ${DIFF=diff}
+    ${DIFF} pascalprog.oku pascalprog.out || exit 1
+  fi
+  if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
+    if test -f /usr/bin/localedef; then
+      echo "Skipping test: no french locale is installed"
+    else
+      echo "Skipping test: no french locale is supported"
+    fi
+    exit 77
+  fi
+else
+  if test $LOCALE_FR = none; then
+    if test -f /usr/bin/localedef; then
+      echo "Skipping test: no traditional french locale is installed"
+    else
+      echo "Skipping test: no traditional french locale is supported"
+    fi
+    exit 77
+  fi
 fi
-if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
-  rm -fr $tmpfiles; exit 77
-fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext/gettext-tools/tests/lang-php b/gettext/gettext-tools/tests/lang-php
--- a/gettext/gettext-tools/tests/lang-php
+++ b/gettext/gettext-tools/tests/lang-php
@@ -1,30 +1,26 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the PHP language.
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: mod_php4-core.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.php"
 cat <<\EOF > prog.php
-<?
+<?php
   setlocale (LC_ALL, "");
   textdomain ("prog");
   bindtextdomain ("prog", ".");
   echo _("'Your command, please?', asked the waiter.");
   echo "\n";
-  echo printf(_("%s is replaced by %s."), "FF", "EUR");
+  printf(_("%s is replaced by %s."), "FF", "EUR");
   echo "\n";
 ?>
 EOF
 
-tmpfiles="$tmpfiles prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --no-location prog.php
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog.php || exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -37,7 +33,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} prog.ok prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
 cat <<\EOF > fr.po
 msgid ""
 msgstr "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -51,31 +46,37 @@ msgid "%s is replaced by %s."
 msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
 ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
-# Test for presence of php version 4.0 or newer.
-case `(php -v) 2>/dev/null` in
+# Test for presence of php version 4.0 or newer with gettext support.
+(php -v) >/dev/null 2>/dev/null
+test $? -le 1 \
+  || { echo "Skipping test: php not found"; exit 77; }
+case `php -v | sed -n -e 1p | sed -e 's/^[^0-9]*//'` in
   [4-9].*) ;;
-  *) rm -fr $tmpfiles; exit 77;;
+  *) echo "Skipping test: php version too old"; exit 77;;
 esac
+{ php -m | grep '^gettext$' >/dev/null; } \
+  || { echo "Skipping test: php was built without gettext support"
+       exit 77
+     }
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LC_ALL=$LOCALE_FR ./testlocale
+  LC_ALL=$LOCALE_FR ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
@@ -83,7 +84,7 @@ if test $LOCALE_FR != none; then
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LC_ALL=$LOCALE_FR_UTF8 ./testlocale
+  LC_ALL=$LOCALE_FR_UTF8 ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
@@ -91,10 +92,14 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
-  rm -fr $tmpfiles; exit 77
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
+  exit 77
 fi
 
-tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
 : ${DIFF=diff}
 cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -108,14 +113,14 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
+  prepare_locale_ fr $LOCALE_FR
   LANGUAGE= LC_ALL=$LOCALE_FR php -q prog.php > prog.out || exit 1
   ${DIFF} prog.ok prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
+  prepare_locale_ fr $LOCALE_FR_UTF8
   LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 php -q prog.php > prog.out || exit 1
   ${DIFF} prog.oku prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext/gettext-tools/tests/lang-python-1 b/gettext/gettext-tools/tests/lang-python-1
--- a/gettext/gettext-tools/tests/lang-python-1
+++ b/gettext/gettext-tools/tests/lang-python-1
@@ -1,16 +1,13 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the Python language.
 
 # Note: This test fails with Python 2.3, 2.4 when an UTF-8 locale is present.
 # It looks like a bug in Python's gettext.py. This here is a quick workaround:
-LOCALE_FR_UTF8=none
+UTF8_LOCALE_UNSUPPORTED=yes
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.py"
-cat <<\EOF > prog.py
+cat <<\EOF > prog1.py
 import gettext
 
 gettext.textdomain('prog')
@@ -21,11 +18,10 @@ print gettext.gettext("%(oldCurrency)s is replaced by %(newCurrency)s.") \
       % { 'oldCurrency': "FF", 'newCurrency' : "EUR" }
 EOF
 
-tmpfiles="$tmpfiles prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.pot --omit-header --no-location prog.py
+${XGETTEXT} -o prog.tmp --omit-header --no-location prog1.py || exit 1
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
 cat <<EOF > prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
@@ -38,7 +34,6 @@ EOF
 : ${DIFF=diff}
 ${DIFF} prog.ok prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
 cat <<\EOF > fr.po
 msgid ""
 msgstr ""
@@ -54,14 +49,13 @@ msgid "%(oldCurrency)s is replaced by %(newCurrency)s."
 msgstr "%(newCurrency)s remplace %(oldCurrency)s."
 EOF
 
-tmpfiles="$tmpfiles fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.new fr.po prog.pot
+${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot || exit 1
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new || exit 1
 
 : ${DIFF=diff}
 ${DIFF} fr.po fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
 test -d fr || mkdir fr
 test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 
@@ -70,13 +64,12 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of python version 2.0 or newer.
 (python -V) >/dev/null 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: python not found"; exit 77; }
 case `python -c 'import sys; print sys.hexversion >= 0x20000F0'` in
   1 | True) ;;
-  *) rm -fr $tmpfiles; exit 77;;
+  *) echo "Skipping test: python version too old"; exit 77;;
 esac
 
-tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
 : ${DIFF=diff}
 cat <<\EOF > prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
@@ -90,17 +83,33 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR python prog.py > prog.out || exit 1
+  prepare_locale_ fr $LOCALE_FR
+  LANGUAGE= LC_ALL=$LOCALE_FR python prog1.py > prog.out || exit 1
   ${DIFF} prog.ok prog.out || exit 1
 fi
-if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 python prog.py > prog.out || exit 1
-  ${DIFF} prog.oku prog.out || exit 1
+if test -z "$UTF8_LOCALE_UNSUPPORTED"; then
+  if test $LOCALE_FR_UTF8 != none; then
+    prepare_locale_ fr $LOCALE_FR_UTF8
+    LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 python prog1.py > prog.out || exit 1
+    ${DIFF} prog.oku prog.out || exit 1
+  fi
+  if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
+    if test -f /usr/bin/localedef; then
+      echo "Skipping test: no french locale is installed"
+    else
+      echo "Skipping test: no french locale is supported"
+    fi
+    exit 77
+  fi
+else
+  if test $LOCALE_FR = none; then
+    if test -f /usr/bin/localedef; then
+      echo "Skipping test: no traditional french locale is installed"
+    else
+      echo "Skipping test: no traditional french locale is supported"
+    fi
+    exit 77
+  fi
 fi
-if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
-  rm -fr $tmpfiles; exit 77
-fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext/gettext-tools/tests/msgunfmt-csharp-1 b/gettext/gettext-tools/tests/msgunfmt-csharp-1
--- a/gettext/gettext-tools/tests/msgunfmt-csharp-1
+++ b/gettext/gettext-tools/tests/msgunfmt-csharp-1
@@ -1,15 +1,25 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of --csharp option.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
 # Test whether we can compile and execute C# programs.
-test "${TESTCSHARP}" = yes || exit 77
+test "${CSHARP_CHOICE}" != no || {
+  echo "Skipping test: configured with --disable-csharp"
+  exit 77
+}
+test "${BUILDCSHARP}" = yes || {
+  echo "Skipping test: C# compiler not found"
+  exit 77
+}
+test "${TESTCSHARP}" = yes || {
+  echo "Skipping test: C# engine not found"
+  exit 77
+}
 
-tmpfiles="$tmpfiles fr.po"
-cat <<\EOF > fr.po
+test -d mu-cs-1 || mkdir mu-cs-1
+
+cat <<\EOF > mu-cs-1/fr.po
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -29,25 +39,30 @@ msgstr[1] "{0} morceaux de gateau"
 #, csharp-format
 msgid "{0} is replaced by {1}."
 msgstr "{1} remplace {0}."
+
+# A proximity measure.
+msgid "Close"
+msgstr "Proche"
+
+# A menu entry.
+msgctxt "File"
+msgid "Close"
+msgstr "Fermer"
 EOF
 
-tmpfiles="$tmpfiles fr/prog.resources.dll"
 : ${MSGFMT=msgfmt}
-GETTEXTCSHARPLIBDIR=../../gettext-runtime/intl-csharp \
-${MSGFMT} --csharp -d . -r prog -l fr fr.po || exit 1
+GETTEXTCSHARPLIBDIR=../../../gettext-runtime/intl-csharp \
+${MSGFMT} --csharp -d mu-cs-1 -r prog -l fr mu-cs-1/fr.po || exit 1
 
-tmpfiles="$tmpfiles prog.out"
 : ${MSGUNFMT=msgunfmt}
-GETTEXTCSHARPEXEDIR=../src \
-GETTEXTCSHARPLIBDIR=../../gettext-runtime/intl-csharp \
-${MSGUNFMT} --csharp -d . -r prog -l fr -o prog.out || exit 1
+GETTEXTCSHARPEXEDIR=../../src \
+GETTEXTCSHARPLIBDIR=../../../gettext-runtime/intl-csharp \
+${MSGUNFMT} --csharp -d mu-cs-1 -r prog -l fr -o mu-cs-1/prog.out || exit 1
 
-tmpfiles="$tmpfiles prog.sort"
 : ${MSGCAT=msgcat}
-${MSGCAT} -s prog.out -o prog.sort || exit 1
+${MSGCAT} -s -o mu-cs-1/prog.sort mu-cs-1/prog.out || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
-cat <<\EOF > prog.ok
+cat <<\EOF > mu-cs-1/prog.ok
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=UTF-8\n"
@@ -55,6 +70,13 @@ msgstr ""
 
 msgid "'Your command, please?', asked the waiter."
 msgstr "«Votre commande, s'il vous plait», dit le garçon."
+
+msgid "Close"
+msgstr "Proche"
+
+msgctxt "File"
+msgid "Close"
+msgstr "Fermer"
 
 msgid "a piece of cake"
 msgid_plural "{0} pieces of cake"
@@ -65,8 +87,6 @@ msgid "{0} is replaced by {1}."
 msgstr "{1} remplace {0}."
 EOF
 : ${DIFF=diff}
-${DIFF} prog.ok prog.sort || exit 1
-
-rm -fr $tmpfiles
+${DIFF} mu-cs-1/prog.ok mu-cs-1/prog.sort || exit 1
 
 exit 0
diff --git a/gettext/gettext-tools/tests/msgunfmt-java-1 b/gettext/gettext-tools/tests/msgunfmt-java-1
--- a/gettext/gettext-tools/tests/msgunfmt-java-1
+++ b/gettext/gettext-tools/tests/msgunfmt-java-1
@@ -1,18 +1,28 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of --java option.
 
 # Note: This test fails when using gcj from GCC 3.1 and GCC 3.2, due to a bug
 # (libgcj/6576). It is fixed in GCC 3.3.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
 # Test whether we can compile and execute Java programs.
-test "${TESTJAVA}" = yes || exit 77
+test "${JAVA_CHOICE}" != no || {
+  echo "Skipping test: configured with --disable-java"
+  exit 77
+}
+test "${BUILDJAVA}" = yes || {
+  echo "Skipping test: Java compiler or jar not found"
+  exit 77
+}
+test "${TESTJAVA}" = yes || {
+  echo "Skipping test: Java engine not found"
+  exit 77
+}
 
-tmpfiles="$tmpfiles fr.po"
-cat <<\EOF > fr.po
+test -d mu-java-1 || mkdir mu-java-1
+
+cat <<\EOF > mu-java-1/fr.po
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -32,24 +42,29 @@ msgstr[1] "{0,number} morceaux de gateau"
 #, java-format
 msgid "{0} is replaced by {1}."
 msgstr "{1} remplace {0}."
+
+# A proximity measure.
+msgid "Close"
+msgstr "Proche"
+
+# A menu entry.
+msgctxt "File"
+msgid "Close"
+msgstr "Fermer"
 EOF
 
-tmpfiles="$tmpfiles prog_fr.class"
 : ${MSGFMT=msgfmt}
-${MSGFMT} -j -d . -r prog -l fr fr.po || exit 1
+${MSGFMT} -j -d mu-java-1 -r prog -l fr mu-java-1/fr.po || exit 1
 
-tmpfiles="$tmpfiles prog.out"
 : ${MSGUNFMT=msgunfmt}
-CLASSPATH=.${CLASSPATH:+:$CLASSPATH} \
-GETTEXTJEXEDIR=../src GETTEXTJAR=../src/gettext.jar \
-${MSGUNFMT} --java -d . -r prog -l fr -o prog.out || exit 1
+CLASSPATH=mu-java-1${CLASSPATH:+:$CLASSPATH} \
+GETTEXTJEXEDIR=../../src GETTEXTJAR=../../src/gettext.jar \
+${MSGUNFMT} --java -d mu-java-1 -r prog -l fr -o mu-java-1/prog.out || exit 1
 
-tmpfiles="$tmpfiles prog.sort"
 : ${MSGCAT=msgcat}
-${MSGCAT} -s prog.out -o prog.sort || exit 1
+${MSGCAT} -s -o mu-java-1/prog.sort mu-java-1/prog.out || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
-cat <<\EOF > prog.ok
+cat <<\EOF > mu-java-1/prog.ok
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=UTF-8\n"
@@ -57,6 +72,13 @@ msgstr ""
 
 msgid "'Your command, please?', asked the waiter."
 msgstr "«Votre commande, s'il vous plait», dit le garçon."
+
+msgid "Close"
+msgstr "Proche"
+
+msgctxt "File"
+msgid "Close"
+msgstr "Fermer"
 
 msgid "a piece of cake"
 msgid_plural "{0,number} pieces of cake"
@@ -67,8 +89,6 @@ msgid "{0} is replaced by {1}."
 msgstr "{1} remplace {0}."
 EOF
 : ${DIFF=diff}
-${DIFF} prog.ok prog.sort || exit 1
-
-rm -fr $tmpfiles
+${DIFF} mu-java-1/prog.ok mu-java-1/prog.sort || exit 1
 
 exit 0
