Bug 18798: make xulrunner easier to build, with target that make more sense. r=mook
git-svn-id: http://publicsvn.songbirdnest.com/vendor/trunk@10911 37441250-4157-47a9-a2c9-f9fe3212d2d3

diff --git a/xulrunner/Makefile.songbird b/xulrunner/Makefile.songbird
--- a/xulrunner/Makefile.songbird
+++ b/xulrunner/Makefile.songbird
@@ -35,7 +35,7 @@ SB_VENDOR_TARGET_VERSION = 1.9.0.15
 
 SB_VENDOR_TARGET_DEP_MODULES := $(NULL)
 
-SB_XR_BRANCH = trunk
+SB_XR_BRANCH ?= trunk
 
 include $(CURDIR)/../songbird-vendor-defs.mk
 
@@ -48,36 +48,68 @@ XR_STRIP_SYMBOLS = $(CURDIR)/xr_strip_symbols.sh
 XR_PACKAGE_DEPS = $(CURDIR)/xr_pack_deps.sh
 XR_CLENAUP = $(CURDIR)/xr_cleanup.sh
 
-xr-all:
-	$(RM) -rf $(CURDIR)/songbird
+# These are named weird because the targets construct these variable names
+HAVE_XR_release_BUILD = test -d $(CURDIR)/mozilla/compiled/xulrunner-release
+HAVE_XR_debug_BUILD = test -d $(CURDIR)/mozilla/compiled/xulrunner-debug
+
+xr-all: xr-clean xr-build-debug xr-build-release xr-symbols xr-packaging
+ifdef XR_CLEAN_OBJDIRS
 	$(RM) -rf $(CURDIR)/mozilla/compiled
-	$(MKDIR) $(SB_VENDOR_BUILD_DIR)
-	$(MAKE) -f $(SB_VENDOR_MAKEFILE) xr-debug
-	$(MAKE) -f $(SB_VENDOR_MAKEFILE) xr-release
+else
+	echo "Define XP_CLEAN_OBJDIRS to remove the (relatively large) xulrunner object directories (assuming if you don't need them and want to recover some space."
+endif
+
+xr-symbols:
+ifndef XR_DISABLE_SYMBOLS
+	@if ! $(HAVE_XR_release_BUILD); then \
+      echo xr-symbols cannot be built before a xulrunner release-build exists.; \
+      echo Build the xr-release target first. Bailing.; \
+      exit -1; \
+   fi
 	# Only build symbols for release builds 
 	$(MAKE) -C $(CURDIR)/mozilla/compiled/xulrunner-release buildsymbols
-ifneq (linux-x86_64,$(SB_TARGET_ARCH))
-	$(MV) $(CURDIR)/mozilla/compiled/xulrunner-release/dist/crashreporter-symbols/crashreporter-symbols-xulrunner-$(SB_VENDOR_TARGET_VERSION)-*.zip $(SB_VENDOR_BUILD_DIR)
+   ifneq (linux-x86_64,$(SB_TARGET_ARCH))
+	   $(MV) $(CURDIR)/mozilla/compiled/xulrunner-release/dist/crashreporter-symbols/crashreporter-symbols-xulrunner-$(SB_VENDOR_TARGET_VERSION)-*.zip $(SB_VENDOR_BUILD_DIR)
+   endif
 endif
-	cd $(CURDIR)/mozilla && $(XR_STRIP_SYMBOLS) $(SB_XR_PLATFORM)
-	$(XR_PACKAGE_DEPS) $(SB_XR_PLATFORM)-$(SB_XR_ARCH) $(SB_XR_BRANCH)
-	# Move these files where we expect them to be in the vendor build system
-	$(MV) $(CURDIR)/songbird/$(SB_XR_BRANCH)/dependencies/$(SB_XR_PLATFORM)-$(SB_XR_ARCH)/mozilla  $(SB_VENDOR_BINARIES_DIR)/mozilla
-	$(MV) $(CURDIR)/songbird/$(SB_XR_BRANCH)/dependencies/$(SB_XR_PLATFORM)-$(SB_XR_ARCH)/xulrunner $(SB_VENDOR_BINARIES_DIR)/xulrunner
+
+xr-packaging: xr-packaging-debug xr-packaging-release
 ifneq (,$(SB_VENDOR_BUILD_LOG))
 	$(CP) $(CURDIR)/$(SB_VENDOR_BUILD_LOG) $(SB_VENDOR_BINARIES_DIR)/xulrunner
 endif
-	# These files aren't needed after the package-deps and take up TONS of space
+
+xr-clean: FORCE
+	$(RM) -rf $(CURDIR)/songbird
 	$(RM) -rf $(CURDIR)/mozilla/compiled
 
-xr-%:
+xr-packaging-%:
+	@echo "Packaging up $*-mode xulrunner..."
+	@if test "release" = "$*"; then \
+      if $(HAVE_XR_release_BUILD); then \
+         cd $(CURDIR)/mozilla && $(XR_STRIP_SYMBOLS) $(SB_XR_PLATFORM); \
+      else \
+         echo "Could not find release build to strip symbols in" 1>&2; \
+      fi; \
+   fi
+	@if $(HAVE_XR_$*_BUILD); then \
+      $(call sh_make,$(XR_PACKAGE_DEPS) $(SB_XR_PLATFORM)-$(SB_XR_ARCH) $(SB_XR_BRANCH) $*); \
+      $(call sh_make,$(RM) -r $(SB_VENDOR_BINARIES_DIR)/mozilla/$*); \
+      $(call sh_make,$(MKDIR) $(SB_VENDOR_BINARIES_DIR)/mozilla/$*); \
+      $(call sh_make,$(MV) $(CURDIR)/songbird/$(SB_XR_BRANCH)/dependencies/$(SB_XR_PLATFORM)-$(SB_XR_ARCH)/mozilla/$* $(SB_VENDOR_BINARIES_DIR)/mozilla/$*); \
+      $(call sh_make,$(RM) -r $(SB_VENDOR_BINARIES_DIR)/xulrunner/$*); \
+      $(call sh_make,$(MKDIR) $(SB_VENDOR_BINARIES_DIR)/xulrunner/$*); \
+      $(call sh_make,$(MV) $(CURDIR)/songbird/$(SB_XR_BRANCH)/dependencies/$(SB_XR_PLATFORM)-$(SB_XR_ARCH)/xulrunner/$* $(SB_VENDOR_BINARIES_DIR)/xulrunner/$*); \
+   fi
+
+xr-build-%:
+	$(MKDIR) $(SB_VENDOR_BUILD_DIR)
 	@echo Setting up xulrunner $*-mode build...
 	$(CP) $(CURDIR)/mozconfigs/$(MOZCONFIG) $(CURDIR)/mozilla/.mozconfig
-	$(RM) -rf $(CURDIR)/mozilla/compiled/xulrunner-$*
+	$(RM) -r $(CURDIR)/mozilla/compiled/xulrunner-$*
 	$(MKDIR) $(CURDIR)/mozilla/compiled/xulrunner-$*
 	$(MAKE) -C $(CURDIR)/mozilla -f client.mk build
 
-.PHONY: xr-all xr-%
+.PHONY: xr-% FORCE
 
 include $(CURDIR)/../songbird-vendor-rules.mk
 
